# Generated by Django 5.2.4 on 2025-11-05 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_delete_dataerasurerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardExport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        max_length=10,
                        verbose_name="Type d'export",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exports/dashboard/%Y/%m/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom du fichier"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paramètres et filtres utilisés pour l'export",
                        verbose_name="Filtres appliqués",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_exports",
                        to="core.societe",
                        verbose_name="Société",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Dashboard",
                "verbose_name_plural": "Exports Dashboard",
                "db_table": "dashboard_exports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="dashboard_e_user_id_e77e49_idx",
                    ),
                    models.Index(
                        fields=["company", "export_type", "-created_at"],
                        name="dashboard_e_company_335313_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("treasury", "Trésorerie"),
                            ("receivables", "Créances"),
                            ("payables", "Dettes"),
                            ("accounting", "Comptabilité"),
                            ("tax", "Fiscalité"),
                            ("system", "Système"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("alert", "Alerte"),
                            ("warning", "Avertissement"),
                            ("info", "Information"),
                            ("success", "Succès"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("read", "Lu"),
                            ("archived", "Archivé"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archivé le"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données supplémentaires (métriques, seuils, etc.)",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Lien vers la page concernée",
                        max_length=500,
                        verbose_name="URL d'action",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_notifications",
                        to="core.societe",
                        verbose_name="Société",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "dashboard_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="dashboard_n_user_id_572c1b_idx",
                    ),
                    models.Index(
                        fields=["company", "severity", "-created_at"],
                        name="dashboard_n_company_e42028_idx",
                    ),
                    models.Index(
                        fields=["category", "is_read"],
                        name="dashboard_n_categor_e351d6_idx",
                    ),
                ],
            },
        ),
    ]
