# Generated by Django 5.2.4 on 2025-10-19 12:47

import apps.crm_clients.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_client", models.CharField(max_length=20, unique=True)),
                ("raison_sociale", models.CharField(max_length=200)),
                ("nom_commercial", models.CharField(blank=True, max_length=200)),
                ("groupe_appartenance", models.CharField(blank=True, max_length=100)),
                (
                    "forme_juridique",
                    models.CharField(
                        choices=[
                            ("SARL", "SARL - Société à Responsabilité Limitée"),
                            ("SAS", "SAS - Société par Actions Simplifiée"),
                            ("SA", "SA - Société Anonyme"),
                            ("SNC", "SNC - Société en Nom Collectif"),
                            (
                                "EURL",
                                "EURL - Entreprise Unipersonnelle à Responsabilité Limitée",
                            ),
                            (
                                "SASU",
                                "SASU - Société par Actions Simplifiée Unipersonnelle",
                            ),
                            ("EI", "EI - Entreprise Individuelle"),
                            ("MICRO", "Micro-entreprise"),
                            ("ASSOCIATION", "Association"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capital_social",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("numero_rcs", models.CharField(blank=True, max_length=20)),
                ("numero_rm", models.CharField(blank=True, max_length=20)),
                (
                    "numero_siret",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le SIRET doit contenir exactement 14 chiffres",
                                regex="^\\d{14}$",
                            )
                        ],
                    ),
                ),
                ("numero_tva", models.CharField(blank=True, max_length=15)),
                ("tva_verifie_vies", models.BooleanField(default=False)),
                ("code_naf", models.CharField(blank=True, max_length=6)),
                ("libelle_naf", models.CharField(blank=True, max_length=200)),
                ("date_creation_societe", models.DateField(blank=True, null=True)),
                (
                    "effectif",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Aucun salarié"),
                            ("1-2", "1 à 2 salariés"),
                            ("3-5", "3 à 5 salariés"),
                            ("6-9", "6 à 9 salariés"),
                            ("10-19", "10 à 19 salariés"),
                            ("20-49", "20 à 49 salariés"),
                            ("50-99", "50 à 99 salariés"),
                            ("100-199", "100 à 199 salariés"),
                            ("200-499", "200 à 499 salariés"),
                            ("500+", "500 salariés et plus"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ca_annuel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<100K", "Moins de 100K€"),
                            ("100K-500K", "100K€ à 500K€"),
                            ("500K-2M", "500K€ à 2M€"),
                            ("2M-10M", "2M€ à 10M€"),
                            ("10M-50M", "10M€ à 50M€"),
                            ("50M+", "Plus de 50M€"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notation_interne",
                    models.CharField(
                        choices=[
                            ("A+", "A+ - Excellent"),
                            ("A", "A - Très bon"),
                            ("B+", "B+ - Bon"),
                            ("B", "B - Acceptable"),
                            ("C", "C - Moyen"),
                            ("D", "D - Risqué"),
                            ("E", "E - Très risqué"),
                        ],
                        default="B",
                        max_length=2,
                    ),
                ),
                (
                    "score_risque",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=apps.crm_clients.models.default_list,
                        help_text="Liste des tags",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_prospect", models.BooleanField(default=False)),
                ("date_premier_contact", models.DateField(blank=True, null=True)),
                (
                    "client_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm_clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="core.societe",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "crm_clients",
                "ordering": ["raison_sociale"],
            },
        ),
        migrations.CreateModel(
            name="ClientAddress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_adresse",
                    models.CharField(
                        choices=[
                            ("SIEGE", "Siège social"),
                            ("FACTURATION", "Facturation"),
                            ("LIVRAISON", "Livraison"),
                            ("CORRESPONDANCE", "Correspondance"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("nom_destinataire", models.CharField(blank=True, max_length=100)),
                ("ligne_1", models.CharField(max_length=100)),
                ("ligne_2", models.CharField(blank=True, max_length=100)),
                ("ligne_3", models.CharField(blank=True, max_length=100)),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(default="France", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("geocodage_valide", models.BooleanField(default=False)),
                ("adresse_validee", models.BooleanField(default=False)),
                ("source_validation", models.CharField(blank=True, max_length=50)),
                ("zone_livraison", models.CharField(blank=True, max_length=50)),
                ("secteur_commercial", models.CharField(blank=True, max_length=50)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="crm_clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse Client",
                "verbose_name_plural": "Adresses Clients",
                "db_table": "crm_client_addresses",
            },
        ),
        migrations.CreateModel(
            name="ClientComptableInfo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sections_analytiques",
                    models.JSONField(
                        default=apps.crm_clients.models.default_dict,
                        help_text="Sections avec répartition",
                    ),
                ),
                (
                    "regime_tva",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Régime normal"),
                            ("SIMPLIFIE", "Régime simplifié"),
                            ("REEL", "Régime réel"),
                            ("FRANCHISE", "Franchise de TVA"),
                            ("INTRACOM", "Intracommunautaire"),
                            ("EXPORT", "Export"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "taux_tva_defaut",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                (
                    "exonerations_tva",
                    models.JSONField(
                        blank=True,
                        default=apps.crm_clients.models.default_list,
                        help_text="Liste des exonérations TVA",
                    ),
                ),
                ("auto_liquidation", models.BooleanField(default=False)),
                ("code_journal_ventes", models.CharField(default="VTE", max_length=10)),
                ("modele_ecriture", models.CharField(blank=True, max_length=50)),
                ("centre_profit", models.CharField(blank=True, max_length=50)),
                ("devise_compte", models.CharField(default="EUR", max_length=3)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comptable_info",
                        to="crm_clients.client",
                    ),
                ),
                (
                    "compte_collectif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients_collectif",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "comptes_analytiques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clients_analytique",
                        to="accounting.chartofaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Information Comptable Client",
                "verbose_name_plural": "Informations Comptables Clients",
                "db_table": "crm_client_comptable_info",
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("KBIS", "Extrait Kbis"),
                            ("RIB", "RIB - Relevé d'Identité Bancaire"),
                            ("CGV", "Conditions Générales de Vente signées"),
                            ("CONTRAT", "Contrat commercial"),
                            ("ASSURANCE", "Attestation d'assurance"),
                            ("MANDAT", "Mandat SEPA"),
                            ("IDENTITE", "Pièce d'identité dirigeant"),
                            ("AUTRE", "Autre document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("fichier", models.FileField(upload_to="clients/documents/%Y/%m/")),
                ("taille_fichier", models.PositiveIntegerField()),
                ("type_mime", models.CharField(max_length=100)),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("date_expiration", models.DateField(blank=True, null=True)),
                ("alerte_expiration_jours", models.IntegerField(default=30)),
                (
                    "contenu_ocr",
                    models.TextField(blank=True, help_text="Contenu extrait par OCR"),
                ),
                (
                    "donnees_extraites",
                    models.JSONField(
                        default=apps.crm_clients.models.default_dict,
                        help_text="Données structurées extraites",
                    ),
                ),
                ("ocr_effectue", models.BooleanField(default=False)),
                ("is_confidentiel", models.BooleanField(default=False)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=apps.crm_clients.models.default_list,
                        help_text="Liste des tags de documents",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="crm_clients.client",
                    ),
                ),
                (
                    "document_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm_clients.clientdocument",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Client",
                "verbose_name_plural": "Documents Clients",
                "db_table": "crm_client_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientFinancialInfo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delai_paiement",
                    models.IntegerField(default=30, help_text="Délai en jours"),
                ),
                (
                    "type_echeance",
                    models.CharField(
                        choices=[
                            ("DATE_FACTURE", "Date de facture"),
                            ("FIN_MOIS", "Fin de mois"),
                            ("FIN_MOIS_CIVIL", "Fin de mois civil"),
                            ("JOUR_FIXE", "Jour fixe du mois"),
                        ],
                        default="DATE_FACTURE",
                        max_length=20,
                    ),
                ),
                (
                    "jour_paiement_fixe",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "taux_escompte",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "delai_escompte",
                    models.IntegerField(
                        default=0, help_text="Délai pour escompte en jours"
                    ),
                ),
                (
                    "modes_reglement",
                    models.JSONField(
                        default=apps.crm_clients.models.default_dict,
                        help_text="Modes acceptés avec priorités",
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("bic", models.CharField(blank=True, max_length=11)),
                ("mandat_sepa_numero", models.CharField(blank=True, max_length=35)),
                ("mandat_sepa_date", models.DateField(blank=True, null=True)),
                (
                    "plafond_encours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "encours_actuel",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "assurance_credit_montant",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "assurance_credit_assureur",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "assurance_credit_police",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "garanties",
                    models.JSONField(
                        default=apps.crm_clients.models.default_list,
                        help_text="Liste des garanties avec détails",
                    ),
                ),
                ("nombre_incidents_6m", models.IntegerField(default=0)),
                ("nombre_incidents_12m", models.IntegerField(default=0)),
                ("dernier_incident", models.DateField(blank=True, null=True)),
                (
                    "periodicite_facturation",
                    models.CharField(default="MENSUELLE", max_length=20),
                ),
                ("regroupement_commandes", models.BooleanField(default=False)),
                ("format_facture", models.CharField(default="PDF", max_length=20)),
                ("mentions_speciales", models.TextField(blank=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_info",
                        to="crm_clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Information Financière Client",
                "verbose_name_plural": "Informations Financières Clients",
                "db_table": "crm_client_financial_info",
            },
        ),
        migrations.CreateModel(
            name="ClientHistorique",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création client"),
                            ("MODIFICATION", "Modification fiche"),
                            ("CONTACT", "Contact commercial"),
                            ("COMMANDE", "Nouvelle commande"),
                            ("FACTURE", "Facturation"),
                            ("PAIEMENT", "Paiement reçu"),
                            ("RELANCE", "Relance envoyée"),
                            ("INCIDENT", "Incident de paiement"),
                            ("LITIGE", "Litige ouvert"),
                            ("RESOLUTION", "Résolution litige"),
                            ("DOCUMENT", "Document ajouté"),
                            ("NOTE", "Note interne"),
                            ("AUTRE", "Autre événement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_evenement", models.DateTimeField(auto_now_add=True)),
                ("objet_lie_type", models.CharField(blank=True, max_length=50)),
                ("objet_lie_id", models.CharField(blank=True, max_length=50)),
                (
                    "donnees_json",
                    models.JSONField(
                        default=apps.crm_clients.models.default_dict,
                        help_text="Données contextuelles",
                    ),
                ),
                (
                    "niveau_importance",
                    models.IntegerField(
                        default=1,
                        help_text="1=Info à 5=Critique",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="crm_clients.client",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Client",
                "verbose_name_plural": "Historiques Clients",
                "db_table": "crm_client_historique",
                "ordering": ["-date_evenement"],
            },
        ),
        migrations.CreateModel(
            name="ClientScoring",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score_global",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "score_paiement",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "score_rentabilite",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "score_potentiel",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "score_risque",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "probabilite_churn",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "customer_lifetime_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("prochaine_commande_estimee", models.DateField(blank=True, null=True)),
                ("segment_ia", models.CharField(blank=True, max_length=50)),
                ("persona_client", models.CharField(blank=True, max_length=50)),
                ("derniere_mise_a_jour", models.DateTimeField(auto_now=True)),
                ("version_algorithme", models.CharField(default="1.0", max_length=10)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring",
                        to="crm_clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoring Client",
                "verbose_name_plural": "Scorings Clients",
                "db_table": "crm_client_scoring",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "civilite",
                    models.CharField(
                        choices=[
                            ("M", "Monsieur"),
                            ("MME", "Madame"),
                            ("MLLE", "Mademoiselle"),
                            ("DR", "Docteur"),
                            ("PROF", "Professeur"),
                        ],
                        max_length=10,
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("fonction", models.CharField(max_length=100)),
                ("service", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("email_principal", models.EmailField(max_length=254)),
                ("email_secondaire", models.EmailField(blank=True, max_length=254)),
                ("telephone_fixe", models.CharField(blank=True, max_length=20)),
                ("telephone_mobile", models.CharField(blank=True, max_length=20)),
                ("telephone_direct", models.CharField(blank=True, max_length=20)),
                ("photo", models.ImageField(blank=True, upload_to="contacts/photos/")),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                (
                    "canal_prefere",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("TELEPHONE", "Téléphone"),
                            ("SMS", "SMS"),
                            ("POSTAL", "Courrier postal"),
                            ("WHATSAPP", "WhatsApp"),
                            ("TEAMS", "Microsoft Teams"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("horaires_preferes", models.CharField(blank=True, max_length=100)),
                (
                    "langue_preferee",
                    models.CharField(
                        choices=[
                            ("FR", "Français"),
                            ("EN", "Anglais"),
                            ("ES", "Espagnol"),
                            ("DE", "Allemand"),
                            ("IT", "Italien"),
                            ("AR", "Arabe"),
                        ],
                        default="FR",
                        max_length=2,
                    ),
                ),
                ("ne_pas_contacter_jusqu", models.DateTimeField(blank=True, null=True)),
                ("date_anniversaire", models.DateField(blank=True, null=True)),
                (
                    "centres_interet_pro",
                    models.JSONField(
                        blank=True,
                        default=apps.crm_clients.models.default_list,
                        help_text="Liste des centres d'intérêt professionnels",
                    ),
                ),
                ("formation", models.CharField(blank=True, max_length=200)),
                (
                    "pourcentage_teletravail",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "jours_presence",
                    models.JSONField(
                        blank=True,
                        default=apps.crm_clients.models.default_list,
                        help_text="Ex: ['LUNDI', 'MARDI', 'MERCREDI']",
                    ),
                ),
                (
                    "pouvoir_decision",
                    models.IntegerField(
                        default=3,
                        help_text="1=Faible à 5=Très fort",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "niveau_interet",
                    models.IntegerField(
                        default=3,
                        help_text="1=Faible à 5=Très fort",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "score_engagement",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("consentement_rgpd", models.BooleanField(default=False)),
                ("date_consentement", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm_clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "crm_contacts",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["code_client"], name="crm_clients_code_cl_d19f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["raison_sociale"], name="crm_clients_raison__2af484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["numero_siret"], name="crm_clients_numero__935b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["notation_interne"], name="crm_clients_notatio_717760_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientaddress",
            unique_together={("client", "type_adresse", "is_default")},
        ),
        migrations.AddIndex(
            model_name="clienthistorique",
            index=models.Index(
                fields=["client", "-date_evenement"],
                name="crm_client__client__065d8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clienthistorique",
            index=models.Index(
                fields=["type_evenement"], name="crm_client__type_ev_0c47b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["client", "is_primary"], name="crm_contact_client__711b61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["email_principal"], name="crm_contact_email_p_e31696_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["nom", "prenom"], name="crm_contact_nom_5eb890_idx"
            ),
        ),
    ]
