# Generated by Django 5.2.8 on 2025-11-28 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_jsonb_to_array(apps, schema_editor):
    """Convertit les champs JSONField en ArrayField via SQL brut."""
    # Skip for SQLite (not PostgreSQL)
    if schema_editor.connection.vendor != 'postgresql':
        return

    conversions = [
        ('crm_clients_client', 'tags', 50),
        ('crm_clients_clientdocument', 'tags', 50),
        ('crm_clients_contact', 'centres_interet_pro', 50),
        ('crm_clients_contact', 'jours_presence', 10),
        ('crm_clients_clientcomptableinfo', 'exonerations_tva', 50),
    ]

    with schema_editor.connection.cursor() as cursor:
        for table, column, max_length in conversions:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_name = %s
                );
            """, [table])
            if not cursor.fetchone()[0]:
                continue

            cursor.execute("""
                SELECT data_type FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s;
            """, [table, column])
            result = cursor.fetchone()
            if not result:
                continue

            current_type = result[0]
            if current_type == 'ARRAY':
                continue

            if current_type == 'jsonb':
                cursor.execute(f"""
                    ALTER TABLE "{table}"
                    ALTER COLUMN "{column}" TYPE varchar({max_length})[]
                    USING (
                        SELECT ARRAY(
                            SELECT jsonb_array_elements_text("{column}")
                        )
                    );
                """)


def reverse_conversion(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("crm_clients", "0001_initial"),
    ]

    operations = [
        # Conversion SQL pour jsonb -> array
        migrations.RunPython(convert_jsonb_to_array, reverse_conversion),
        # Mise à jour de l'état Django uniquement (SeparateDatabaseAndState)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="client",
                    name="tags",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                migrations.AlterField(
                    model_name="clientcomptableinfo",
                    name="exonerations_tva",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                migrations.AlterField(
                    model_name="clientcomptableinfo",
                    name="sections_analytiques",
                    field=models.JSONField(default=dict, help_text="Sections avec répartition"),
                ),
                migrations.AlterField(
                    model_name="clientdocument",
                    name="donnees_extraites",
                    field=models.JSONField(
                        default=dict, help_text="Données structurées extraites"
                    ),
                ),
                migrations.AlterField(
                    model_name="clientdocument",
                    name="tags",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                migrations.AlterField(
                    model_name="clientfinancialinfo",
                    name="garanties",
                    field=models.JSONField(
                        default=list, help_text="Liste des garanties avec détails"
                    ),
                ),
                migrations.AlterField(
                    model_name="clientfinancialinfo",
                    name="modes_reglement",
                    field=models.JSONField(
                        default=dict, help_text="Modes acceptés avec priorités"
                    ),
                ),
                migrations.AlterField(
                    model_name="clienthistorique",
                    name="donnees_json",
                    field=models.JSONField(default=dict, help_text="Données contextuelles"),
                ),
                migrations.AlterField(
                    model_name="contact",
                    name="centres_interet_pro",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                migrations.AlterField(
                    model_name="contact",
                    name="jours_presence",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        help_text="Ex: ['LUNDI', 'MARDI', 'MERCREDI']",
                        size=None,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
