# Generated by Django 5.2.4 on 2025-10-19 12:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlesFiscaux",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_controle", models.CharField(db_index=True, max_length=100)),
                (
                    "type_controle",
                    models.CharField(
                        choices=[
                            ("CONTROLE_SUR_PIECES", "Contrôle sur pièces"),
                            (
                                "VERIFICATION_COMPTABILITE",
                                "Vérification de comptabilité",
                            ),
                            ("CONTROLE_PONCTUEL", "Contrôle ponctuel"),
                            ("CONTROLE_INATTENDU", "Contrôle inattendu"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "exercices_controles",
                    models.CharField(help_text="Ex: 2020-2022", max_length=100),
                ),
                ("date_debut_controle", models.DateField()),
                ("date_fin_controle", models.DateField(blank=True, null=True)),
                ("service_controleur", models.CharField(max_length=200)),
                (
                    "nom_controleur",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lettre_notification",
                    models.FileField(blank=True, null=True, upload_to="controles/"),
                ),
                (
                    "rapport_controle",
                    models.FileField(blank=True, null=True, upload_to="controles/"),
                ),
                (
                    "redressements_proposes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "penalites_proposees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "redressements_acceptes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOTIFIE", "Notifié"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("CONTESTE", "Contesté"),
                            ("CLOTURE", "Clôturé"),
                        ],
                        default="NOTIFIE",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                ("actions_correctives", models.TextField(blank=True, null=True)),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_fiscaux",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrôle fiscal",
                "verbose_name_plural": "Contrôles fiscaux",
                "db_table": "taxation_controle",
                "ordering": ["-date_debut_controle"],
            },
        ),
        migrations.CreateModel(
            name="DeclarationFiscale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_declaration", models.CharField(db_index=True, max_length=50)),
                (
                    "reference_administration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("exercice", models.IntegerField()),
                ("periode_debut", models.DateField()),
                ("periode_fin", models.DateField()),
                ("date_limite_depot", models.DateField()),
                ("date_limite_paiement", models.DateField()),
                (
                    "base_imposable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_impot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_impot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "acompte_verse",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_du",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "penalite_retard",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "majorations",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_COURS", "En cours de saisie"),
                            ("VALIDEE", "Validée"),
                            ("TRANSMISE", "Transmise"),
                            ("ACCEPTEE", "Acceptée par l'administration"),
                            ("REJETEE", "Rejetée"),
                            ("PAYEE", "Payée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("date_transmission", models.DateTimeField(blank=True, null=True)),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                (
                    "fichier_declaration",
                    models.FileField(blank=True, null=True, upload_to="declarations/"),
                ),
                (
                    "accuse_reception",
                    models.FileField(blank=True, null=True, upload_to="accusations/"),
                ),
                (
                    "donnees_declaration",
                    models.JSONField(
                        default=dict, help_text="Données détaillées de la déclaration"
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "commentaires_administration",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations_fiscales",
                        to="core.societe",
                    ),
                ),
                (
                    "transmise_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declarations_transmises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declarations_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration fiscale",
                "verbose_name_plural": "Déclarations fiscales",
                "db_table": "taxation_declaration",
                "ordering": ["-date_limite_depot"],
            },
        ),
        migrations.CreateModel(
            name="DocumentFiscal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("DECLARATION", "Déclaration fiscale"),
                            ("ACCUSE_RECEPTION", "Accusé de réception"),
                            ("AVIS_IMPOSITION", "Avis d'imposition"),
                            ("QUITTANCE", "Quittance de paiement"),
                            ("CORRESPONDANCE", "Correspondance administrative"),
                            ("PIECE_JUSTIFICATIVE", "Pièce justificative"),
                            ("AUTRE", "Autre document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nom_document", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("fichier", models.FileField(upload_to="documents_fiscaux/")),
                ("taille_fichier", models.PositiveIntegerField(editable=False)),
                ("date_document", models.DateField()),
                ("date_reception", models.DateField(blank=True, null=True)),
                (
                    "numero_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("confidentiel", models.BooleanField(default=False)),
                (
                    "controle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="taxation.controlesfiscaux",
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="taxation.declarationfiscale",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_fiscaux",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document fiscal",
                "verbose_name_plural": "Documents fiscaux",
                "db_table": "taxation_document",
                "ordering": ["-date_document"],
            },
        ),
        migrations.CreateModel(
            name="LigneDeclaration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_ligne", models.CharField(max_length=20)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "montant_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taux_applique",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "montant_calcule",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                ("obligatoire", models.BooleanField(default=True)),
                ("calculee_auto", models.BooleanField(default=True)),
                (
                    "formule",
                    models.TextField(
                        blank=True,
                        help_text="Formule de calcul spécifique à cette ligne",
                        null=True,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="taxation.declarationfiscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de déclaration",
                "verbose_name_plural": "Lignes de déclaration",
                "db_table": "taxation_ligne_declaration",
                "ordering": ["ordre", "code_ligne"],
            },
        ),
        migrations.CreateModel(
            name="ObligationFiscale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("debut_obligation", models.DateField()),
                ("fin_obligation", models.DateField(blank=True, null=True)),
                ("rappel_actif", models.BooleanField(default=True)),
                (
                    "nb_jours_rappel",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Nombre de jours avant échéance pour le rappel",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDUE", "Suspendue"),
                            ("TERMINEE", "Terminée"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsable de cette obligation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligations_fiscales",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obligation fiscale",
                "verbose_name_plural": "Obligations fiscales",
                "db_table": "taxation_obligation",
            },
        ),
        migrations.CreateModel(
            name="AlerteFiscale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("ECHEANCE_PROCHE", "Échéance proche"),
                            ("RETARD_DECLARATION", "Retard de déclaration"),
                            ("RETARD_PAIEMENT", "Retard de paiement"),
                            ("CHANGEMENT_REGLEMENTATION", "Changement réglementation"),
                            ("CONTROLE_FISCAL", "Contrôle fiscal"),
                            ("SEUIL_DEPASSE", "Seuil dépassé"),
                            ("AUTRE", "Autre alerte"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                            ("CRITICAL", "Critique"),
                        ],
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("date_echeance", models.DateField(blank=True, null=True)),
                (
                    "montant_concerne",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACQUITTEE", "Acquittée"),
                            ("RESOLUE", "Résolue"),
                            ("IGNOREE", "Ignorée"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_acquittement", models.DateTimeField(blank=True, null=True)),
                ("actions_recommandees", models.JSONField(blank=True, default=list)),
                ("commentaires", models.TextField(blank=True, null=True)),
                (
                    "acquittee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_fiscales",
                        to="core.societe",
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxation.declarationfiscale",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxation.obligationfiscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte fiscale",
                "verbose_name_plural": "Alertes fiscales",
                "db_table": "taxation_alerte",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PlanificationDeclaration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("periode_debut", models.DateField()),
                ("periode_fin", models.DateField()),
                ("date_echeance_depot", models.DateField()),
                ("date_echeance_paiement", models.DateField()),
                ("declaration_generee", models.BooleanField(default=False)),
                ("rappel_envoye", models.BooleanField(default=False)),
                ("date_rappel", models.DateTimeField(blank=True, null=True)),
                (
                    "montant_estime",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant estimé basé sur l'historique",
                        max_digits=15,
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxation.declarationfiscale",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planifications",
                        to="taxation.obligationfiscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planification de déclaration",
                "verbose_name_plural": "Planifications de déclarations",
                "db_table": "taxation_planification",
                "ordering": ["date_echeance_depot"],
            },
        ),
        migrations.CreateModel(
            name="RegimeFiscal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type_regime",
                    models.CharField(
                        choices=[
                            ("RSI", "Régime Simplifié d'Imposition"),
                            ("RNI", "Régime Normal d'Imposition"),
                            ("CGU", "Centre de Gestion Unique"),
                            ("REEL", "Régime du Réel"),
                            ("MICRO", "Régime de la Micro-entreprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "taux_is",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        help_text="Taux d'Impôt sur les Sociétés en %",
                        max_digits=5,
                    ),
                ),
                (
                    "taux_tva_standard",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.25"),
                        help_text="Taux de TVA standard en %",
                        max_digits=5,
                    ),
                ),
                (
                    "taux_tva_reduit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taux de TVA réduit en %",
                        max_digits=5,
                    ),
                ),
                (
                    "seuil_ca_annual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Seuil de chiffre d'affaires annuel",
                        max_digits=15,
                    ),
                ),
                (
                    "plafond_deduc_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Plafond de déduction des charges",
                        max_digits=15,
                    ),
                ),
                (
                    "declarations_obligatoires",
                    models.JSONField(
                        default=list, help_text="Liste des déclarations obligatoires"
                    ),
                ),
                ("date_debut_validite", models.DateField()),
                ("date_fin_validite", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regimes_fiscaux",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Régime fiscal",
                "verbose_name_plural": "Régimes fiscaux",
                "db_table": "taxation_regime_fiscal",
            },
        ),
        migrations.AddField(
            model_name="obligationfiscale",
            name="regime_fiscal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obligations",
                to="taxation.regimefiscal",
            ),
        ),
        migrations.AddField(
            model_name="declarationfiscale",
            name="regime_fiscal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="declarations",
                to="taxation.regimefiscal",
            ),
        ),
        migrations.CreateModel(
            name="TypeDeclaration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("MENSUELLE", "Mensuelle"),
                            ("BIMESTRIELLE", "Bimestrielle"),
                            ("TRIMESTRIELLE", "Trimestrielle"),
                            ("SEMESTRIELLE", "Semestrielle"),
                            ("ANNUELLE", "Annuelle"),
                            ("EXCEPTIONNELLE", "Exceptionnelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OBLIGATOIRE", "Obligatoire"),
                            ("FACULTATIVE", "Facultative"),
                            ("CONDITIONNELLE", "Conditionnelle"),
                        ],
                        default="OBLIGATOIRE",
                        max_length=20,
                    ),
                ),
                (
                    "jour_echeance",
                    models.PositiveIntegerField(
                        default=15, help_text="Jour du mois d'échéance"
                    ),
                ),
                (
                    "mois_offset",
                    models.IntegerField(
                        default=1, help_text="Offset en mois par rapport à la période"
                    ),
                ),
                (
                    "formule_calcul",
                    models.TextField(
                        blank=True,
                        help_text="Formule de calcul de l'impôt/taxe",
                        null=True,
                    ),
                ),
                (
                    "taux_penalite_retard",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Taux de pénalité de retard en %",
                        max_digits=5,
                    ),
                ),
                (
                    "penalite_fixe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pénalité fixe en cas de retard",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                (
                    "comptes_base_calcul",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Comptes servant de base au calcul",
                        to="accounting.chartofaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de déclaration",
                "verbose_name_plural": "Types de déclarations",
                "db_table": "taxation_type_declaration",
                "ordering": ["ordre_affichage", "libelle"],
            },
        ),
        migrations.AddField(
            model_name="obligationfiscale",
            name="type_declaration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obligations",
                to="taxation.typedeclaration",
            ),
        ),
        migrations.CreateModel(
            name="EvenementFiscal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création d'entreprise"),
                            ("MODIFICATION", "Modification statuts"),
                            ("FUSION", "Fusion"),
                            ("SCISSION", "Scission"),
                            ("DISSOLUTION", "Dissolution"),
                            ("CHANGEMENT_REGIME", "Changement de régime"),
                            ("CHANGEMENT_ACTIVITE", "Changement d'activité"),
                            ("AUTRE", "Autre événement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_evenement", models.DateField()),
                (
                    "date_effet_fiscal",
                    models.DateField(help_text="Date d'effet fiscal de l'événement"),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "obligations_specifiques",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Obligations fiscales spécifiques liées à l'événement",
                    ),
                ),
                ("traite", models.BooleanField(default=False)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("pieces_justificatives", models.JSONField(blank=True, default=list)),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements_fiscaux",
                        to="core.societe",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nouveau_regime",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nouveau régime fiscal si applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxation.regimefiscal",
                    ),
                ),
                (
                    "declarations_impactees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Types de déclarations impactées",
                        to="taxation.typedeclaration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement fiscal",
                "verbose_name_plural": "Événements fiscaux",
                "db_table": "taxation_evenement_fiscal",
                "ordering": ["-date_evenement"],
            },
        ),
        migrations.AddField(
            model_name="declarationfiscale",
            name="type_declaration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="declarations",
                to="taxation.typedeclaration",
            ),
        ),
        migrations.AddIndex(
            model_name="controlesfiscaux",
            index=models.Index(
                fields=["societe", "statut"], name="taxation_co_societe_54cc43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlesfiscaux",
            index=models.Index(
                fields=["date_debut_controle"], name="taxation_co_date_de_0fee6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlesfiscaux",
            index=models.Index(
                fields=["type_controle"], name="taxation_co_type_co_3a41fa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="controlesfiscaux",
            unique_together={("societe", "numero_controle")},
        ),
        migrations.AddIndex(
            model_name="documentfiscal",
            index=models.Index(
                fields=["societe", "type_document"],
                name="taxation_do_societe_d93b99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfiscal",
            index=models.Index(
                fields=["date_document"], name="taxation_do_date_do_4317e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfiscal",
            index=models.Index(
                fields=["declaration"], name="taxation_do_declara_52763c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfiscal",
            index=models.Index(
                fields=["controle"], name="taxation_do_control_e917e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lignedeclaration",
            index=models.Index(
                fields=["declaration", "ordre"], name="taxation_li_declara_6a8c40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lignedeclaration",
            index=models.Index(
                fields=["compte"], name="taxation_li_compte__a7a199_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lignedeclaration",
            unique_together={("declaration", "code_ligne")},
        ),
        migrations.AddIndex(
            model_name="alertefiscale",
            index=models.Index(
                fields=["societe", "statut"], name="taxation_al_societe_c9b939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertefiscale",
            index=models.Index(
                fields=["type_alerte", "niveau"], name="taxation_al_type_al_cb7b9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertefiscale",
            index=models.Index(
                fields=["date_creation"], name="taxation_al_date_cr_25dbb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertefiscale",
            index=models.Index(
                fields=["date_echeance"], name="taxation_al_date_ec_17fe56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planificationdeclaration",
            index=models.Index(
                fields=["date_echeance_depot"], name="taxation_pl_date_ec_137cf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planificationdeclaration",
            index=models.Index(
                fields=["declaration_generee"], name="taxation_pl_declara_4711d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planificationdeclaration",
            index=models.Index(
                fields=["rappel_envoye"], name="taxation_pl_rappel__ee72f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planificationdeclaration",
            unique_together={("obligation", "periode_debut")},
        ),
        migrations.AddIndex(
            model_name="regimefiscal",
            index=models.Index(
                fields=["societe", "type_regime"], name="taxation_re_societe_514ba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regimefiscal",
            index=models.Index(
                fields=["date_debut_validite", "date_fin_validite"],
                name="taxation_re_date_de_48b998_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="regimefiscal",
            unique_together={("societe", "code")},
        ),
        migrations.AddIndex(
            model_name="obligationfiscale",
            index=models.Index(
                fields=["societe", "statut"], name="taxation_ob_societe_454231_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="obligationfiscale",
            index=models.Index(
                fields=["debut_obligation", "fin_obligation"],
                name="taxation_ob_debut_o_b66f1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="obligationfiscale",
            index=models.Index(
                fields=["responsable"], name="taxation_ob_respons_afa205_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="obligationfiscale",
            unique_together={("societe", "type_declaration", "regime_fiscal")},
        ),
        migrations.AddIndex(
            model_name="evenementfiscal",
            index=models.Index(
                fields=["societe", "date_evenement"],
                name="taxation_ev_societe_2278df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evenementfiscal",
            index=models.Index(
                fields=["type_evenement"], name="taxation_ev_type_ev_f8dd5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evenementfiscal",
            index=models.Index(fields=["traite"], name="taxation_ev_traite_1b9091_idx"),
        ),
        migrations.AddIndex(
            model_name="declarationfiscale",
            index=models.Index(
                fields=["societe", "exercice", "statut"],
                name="taxation_de_societe_3fb7f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="declarationfiscale",
            index=models.Index(
                fields=["type_declaration", "periode_debut"],
                name="taxation_de_type_de_3468a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="declarationfiscale",
            index=models.Index(
                fields=["date_limite_depot"], name="taxation_de_date_li_37aed9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="declarationfiscale",
            index=models.Index(fields=["statut"], name="taxation_de_statut_2a9818_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="declarationfiscale",
            unique_together={("societe", "numero_declaration")},
        ),
    ]
