# Generated by Django 4.2.7 on 2025-10-08 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Devise",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code ISO"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("symbole", models.CharField(max_length=10, verbose_name="Symbole")),
                (
                    "taux_change",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "db_table": "core_devise",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Societe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Raison sociale"),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Société",
                "verbose_name_plural": "Sociétés",
                "db_table": "core_companies",
                "ordering": ["nom"],
            },
        ),
    ]
