# Generated by Django 5.2.4 on 2025-10-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_EXECUTION", "Exécution paiement"),
                            ("PAYMENT_APPROVAL", "Approbation paiement"),
                            ("USER_DELETION", "Suppression utilisateur"),
                            ("SETTINGS_CHANGE", "Modification paramètres critiques"),
                            ("DATA_EXPORT", "Export données sensibles"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Données de l'opération (payment_id, amount, etc.)",
                    ),
                ),
                ("challenge_code", models.CharField(max_length=64, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_mfa_challenges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFAMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("TOTP", "Application Authenticator (TOTP)"),
                            ("SMS", "SMS (future)"),
                            ("EMAIL", "Email (future)"),
                        ],
                        default="TOTP",
                        max_length=10,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Secret TOTP base32 encoded", max_length=32
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default="Authenticator",
                        help_text="Nom de la méthode (ex: iPhone, Android)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.IntegerField(default=0)),
                (
                    "backup_codes",
                    models.JSONField(
                        default=list, help_text="10 codes de secours à usage unique"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_mfa_methods",
                "ordering": ["-is_active", "-created_at"],
                "unique_together": {("user", "method_type")},
            },
        ),
    ]
