# Generated by Django 5.2.4 on 2025-10-24 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_mfachallenge_mfamethod"),
    ]

    operations = [
        migrations.CreateModel(
            name='DataErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Raison de la suppression')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Terminée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_deleted', models.IntegerField(default=0)),
                ('records_anonymized', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('report', models.JSONField(default=dict, help_text='Rapport détaillé de la suppression')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_erasure_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_data_erasure_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
