# Generated by Django 5.2.4 on 2025-11-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_gdpr_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataErasureRequest",
        ),
    ]
