# Generated by Django 5.2.8 on 2025-11-28 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_delete_dataerasurerequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mfamethod",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="mfamethod",
            name="user",
        ),
        migrations.DeleteModel(
            name="MFAChallenge",
        ),
        migrations.DeleteModel(
            name="MFAMethod",
        ),
    ]
