# Generated by Django 4.2.7 on 2025-10-08 08:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=9,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "account_class",
                    models.CharField(
                        choices=[
                            ("1", "Classe 1 - Comptes de capitaux"),
                            ("2", "Classe 2 - Comptes d'immobilisations"),
                            ("3", "Classe 3 - Comptes de stocks"),
                            ("4", "Classe 4 - Comptes de tiers"),
                            ("5", "Classe 5 - Comptes de trésorerie"),
                            ("6", "Classe 6 - Comptes de charges"),
                            ("7", "Classe 7 - Comptes de produits"),
                            ("8", "Classe 8 - Comptes spéciaux"),
                            ("9", "Classe 9 - Comptabilité analytique"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("DETAIL", "Compte de détail"),
                            ("TOTAL", "Compte de total"),
                            ("AUXILIARY", "Compte auxiliaire"),
                        ],
                        default="DETAIL",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(default=0, help_text="Niveau hiérarchique"),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("DEBIT", "Débit"), ("CREDIT", "Crédit")],
                        default="DEBIT",
                        max_length=6,
                    ),
                ),
                (
                    "is_reconcilable",
                    models.BooleanField(default=False, verbose_name="Lettrable"),
                ),
                (
                    "is_auxiliary",
                    models.BooleanField(
                        default=False, verbose_name="Compte auxiliaire"
                    ),
                ),
                (
                    "allow_direct_entry",
                    models.BooleanField(
                        default=True, verbose_name="Saisie directe autorisée"
                    ),
                ),
                (
                    "is_multi_currency",
                    models.BooleanField(default=False, verbose_name="Multi-devises"),
                ),
                ("default_currency", models.CharField(blank=True, max_length=3)),
                (
                    "ifrs_mapping",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Correspondance IFRS"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_chart_of_accounts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Ex: 2024", max_length=10)),
                (
                    "name",
                    models.CharField(help_text="Ex: Exercice 2024", max_length=100),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_fiscal_years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("AC", "Achats"),
                            ("VE", "Ventes"),
                            ("BQ", "Banque"),
                            ("CA", "Caisse"),
                            ("OD", "Opérations Diverses"),
                            ("AN", "À-nouveaux"),
                            ("SAL", "Salaires"),
                            ("DEC", "Déclarations"),
                            ("REG", "Régularisations"),
                            ("CLO", "Clôture"),
                        ],
                        max_length=10,
                        verbose_name="Type de journal",
                    ),
                ),
                (
                    "numbering_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Préfixe pour numérotation automatique",
                        max_length=10,
                    ),
                ),
                (
                    "last_number",
                    models.IntegerField(default=0, help_text="Dernier numéro utilisé"),
                ),
                (
                    "require_validation",
                    models.BooleanField(
                        default=False, verbose_name="Validation obligatoire"
                    ),
                ),
                (
                    "require_attachment",
                    models.BooleanField(
                        default=False, verbose_name="Pièce justificative obligatoire"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_journals",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "piece_number",
                    models.CharField(max_length=50, verbose_name="Numéro de pièce"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence externe"
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="Date d'écriture")),
                (
                    "value_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de valeur"
                    ),
                ),
                ("description", models.TextField(verbose_name="Libellé")),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "is_balanced",
                    models.BooleanField(default=False, verbose_name="Équilibrée"),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validée"),
                ),
                ("validation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "source_document",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Document source"
                    ),
                ),
                (
                    "attachment_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de pièces jointes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "db_table": "accounting_journal_entries",
                "ordering": ["-entry_date", "-piece_number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Libellé")),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "currency_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "reconciliation_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code lettrage"
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(default=False, verbose_name="Lettrée"),
                ),
                ("reconciliation_date", models.DateField(blank=True, null=True)),
                ("line_number", models.IntegerField(default=1)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_lines",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "db_table": "accounting_journal_entry_lines",
                "ordering": ["entry", "line_number"],
            },
        ),
    ]
