# Generated by Django 4.2.7 on 2025-10-08 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("third_party", "0001_initial"),
        ("accounting", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentryline",
            name="third_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entry_lines",
                to="third_party.tiers",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="core.societe",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="accounting.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="accounting.journal",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to="core.societe",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="default_credit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_credit_journals",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="default_debit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_debit_journals",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscal_years",
                to="core.societe",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.societe",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_accounts",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("company", "fiscal_year", "journal", "piece_number")},
        ),
        migrations.AlterUniqueTogether(
            name="journal",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="fiscalyear",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="chartofaccounts",
            unique_together={("company", "code")},
        ),
    ]
