# Generated by Django 5.2.8 on 2025-11-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_initial"),
        ("third_party", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentryline",
            name="third_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entry_lines",
                to="third_party.tiers",
                verbose_name="Tiers",
            ),
        ),
    ]
