# Generated by Django 4.2.7 on 2025-10-17 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametreSysteme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cle", models.CharField(db_index=True, max_length=100, unique=True)),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Général"),
                            ("COMPTABILITE", "Comptabilité"),
                            ("FISCALITE", "Fiscalité"),
                            ("TRESORERIE", "Trésorerie"),
                            ("SECURITE", "Sécurité"),
                            ("INTEGRATION", "Intégration"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("INTERFACE", "Interface"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "type_valeur",
                    models.CharField(
                        choices=[
                            ("STRING", "Texte"),
                            ("INTEGER", "Nombre entier"),
                            ("DECIMAL", "Nombre décimal"),
                            ("BOOLEAN", "Booléen"),
                            ("DATE", "Date"),
                            ("EMAIL", "Email"),
                            ("URL", "URL"),
                            ("JSON", "JSON"),
                            ("COLOR", "Couleur"),
                        ],
                        default="STRING",
                        max_length=20,
                    ),
                ),
                ("valeur", models.TextField()),
                ("valeur_par_defaut", models.TextField()),
                ("requis", models.BooleanField(default=False)),
                ("modifiable_runtime", models.BooleanField(default=True)),
                ("visible_interface", models.BooleanField(default=True)),
                ("regex_validation", models.CharField(blank=True, max_length=500)),
                ("valeurs_autorisees", models.JSONField(blank=True, default=list)),
                (
                    "valeur_min",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "valeur_max",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("groupe", models.CharField(blank=True, max_length=100)),
                ("ordre", models.IntegerField(default=0)),
                ("aide", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Paramètre Système",
                "verbose_name_plural": "Paramètres Système",
                "db_table": "parametres_systeme",
                "ordering": ["categorie", "groupe", "ordre", "nom"],
                "indexes": [
                    models.Index(
                        fields=["categorie", "groupe"],
                        name="parametres__categor_40b0fb_idx",
                    ),
                    models.Index(fields=["cle"], name="parametres__cle_1d6d34_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationParametres",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evenement",
                    models.CharField(
                        choices=[
                            ("CONNEXION_ECHEC", "Échec de connexion"),
                            ("SAUVEGARDE", "Sauvegarde système"),
                            ("CLOTURE_PERIODE", "Clôture de période"),
                            ("VALIDATION_ECRITURE", "Validation d'écriture"),
                            ("RAPPEL_ECHEANCE", "Rappel d'échéance"),
                            ("ERREUR_INTEGRATION", "Erreur d'intégration"),
                            ("MISE_A_JOUR", "Mise à jour système"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Notification Push"),
                            ("SYSTEME", "Notification Système"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("destinataires", models.JSONField(default=list)),
                ("modele_message", models.TextField()),
                (
                    "delai_envoi",
                    models.IntegerField(default=0, help_text="Délai en minutes"),
                ),
                (
                    "frequence_max",
                    models.IntegerField(default=1, help_text="Nombre max par jour"),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_parametres",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre Notification",
                "verbose_name_plural": "Paramètres Notifications",
                "db_table": "notifications_parametres",
                "unique_together": {("societe", "evenement", "type_notification")},
            },
        ),
        migrations.CreateModel(
            name="JournalParametres",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("libelle", models.CharField(max_length=100)),
                (
                    "type_journal",
                    models.CharField(
                        choices=[
                            ("VENTES", "Journal des Ventes"),
                            ("ACHATS", "Journal des Achats"),
                            ("BANQUE", "Journal de Banque"),
                            ("CAISSE", "Journal de Caisse"),
                            ("OPERATIONS_DIVERSES", "Journal des Opérations Diverses"),
                            ("PAIE", "Journal de Paie"),
                            ("IMMOBILISATIONS", "Journal des Immobilisations"),
                        ],
                        max_length=30,
                    ),
                ),
                ("numerotation_auto", models.BooleanField(default=True)),
                ("prefixe", models.CharField(blank=True, max_length=10)),
                ("suffixe", models.CharField(blank=True, max_length=10)),
                ("compteur", models.IntegerField(default=1)),
                ("nb_chiffres", models.IntegerField(default=6)),
                ("contrepartie_obligatoire", models.BooleanField(default=False)),
                ("lettrage_auto", models.BooleanField(default=False)),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journaux_parametres",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre Journal",
                "verbose_name_plural": "Paramètres Journaux",
                "db_table": "journaux_parametres",
                "unique_together": {("societe", "code")},
            },
        ),
        migrations.CreateModel(
            name="ConfigurationSociete",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("forme_juridique", models.CharField(default="SARL", max_length=50)),
                (
                    "capital_social",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("numero_rccm", models.CharField(blank=True, max_length=50)),
                ("numero_contribuable", models.CharField(blank=True, max_length=50)),
                (
                    "plan_comptable_type",
                    models.CharField(
                        choices=[
                            ("SYSCOHADA_NORMAL", "SYSCOHADA Normal"),
                            ("SYSCOHADA_MINIMAL", "SYSCOHADA Minimal"),
                            ("SYSCOHADA_BANQUE", "SYSCOHADA Bancaire"),
                            ("SYSCOHADA_ASSURANCE", "SYSCOHADA Assurance"),
                        ],
                        default="SYSCOHADA_NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "devise_principale",
                    models.CharField(
                        default="XAF",
                        help_text="Code ISO 4217 de la devise (XAF, EUR, USD, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "nb_decimales",
                    models.IntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "debut_exercice",
                    models.CharField(
                        default="01-01", help_text="Format MM-DD", max_length=5
                    ),
                ),
                (
                    "fin_exercice",
                    models.CharField(
                        default="12-31", help_text="Format MM-DD", max_length=5
                    ),
                ),
                (
                    "regime_fiscal",
                    models.CharField(
                        choices=[
                            ("REEL", "Régime du Réel"),
                            ("SIMPLIFIE", "Régime Simplifié"),
                            ("SYNTHETIQUE", "Régime de Synthèse"),
                        ],
                        default="REEL",
                        max_length=20,
                    ),
                ),
                ("assujetti_tva", models.BooleanField(default=True)),
                (
                    "taux_tva_defaut",
                    models.DecimalField(decimal_places=2, default=19.25, max_digits=5),
                ),
                (
                    "duree_session",
                    models.IntegerField(default=60, help_text="Durée en minutes"),
                ),
                ("tentatives_connexion_max", models.IntegerField(default=5)),
                (
                    "duree_blocage",
                    models.IntegerField(default=30, help_text="Durée en minutes"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("TRINITY_LIGHT", "Trinity Clair"),
                            ("TRINITY_DARK", "Trinity Sombre"),
                            ("CLASSIC", "Classique"),
                        ],
                        default="TRINITY_LIGHT",
                        max_length=20,
                    ),
                ),
                (
                    "langue_defaut",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "Anglais"),
                            ("es", "Espagnol"),
                        ],
                        default="fr",
                        max_length=5,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "couleur_principale",
                    models.CharField(default="#7A8B8E", max_length=7),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(default="#353A3B", max_length=7),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Société",
                "verbose_name_plural": "Configurations Société",
                "db_table": "configurations_societe",
                "unique_together": {("societe",)},
            },
        ),
    ]
