# Generated by Django 5.2.4 on 2025-10-19 12:36

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Format: FLO0001 (Fournisseur Local 0001)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^F[A-Z]{2,3}\\d{4,}$",
                                "Format: FLO0001 (Fournisseur Local 0001)",
                            )
                        ],
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("GOODS", "Fournisseur de biens"),
                            ("SERVICES", "Fournisseur de services"),
                            ("SUBCONTRACTOR", "Sous-traitant"),
                            ("CONSULTING", "Conseil/Expertise"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TRANSPORT", "Transport/Logistique"),
                            ("UTILITIES", "Services publics"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(max_length=255, verbose_name="Raison sociale"),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom commercial"
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SA", "Société Anonyme"),
                            ("SARL", "SARL"),
                            ("SAS", "SAS"),
                            ("EI", "Entreprise Individuelle"),
                            ("GIE", "GIE"),
                            ("COOP", "Coopérative"),
                            ("FOREIGN", "Société étrangère"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rccm",
                    models.CharField(blank=True, max_length=50, verbose_name="RCCM"),
                ),
                (
                    "nif",
                    models.CharField(blank=True, max_length=50, verbose_name="NIF"),
                ),
                (
                    "taxpayer_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro contribuable"
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro TVA"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                (
                    "business_sector",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Secteur d'activité"
                    ),
                ),
                ("main_address", models.TextField(verbose_name="Adresse principale")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Région"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Cameroun", max_length=50, verbose_name="Pays"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "main_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="Fax"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Conditions de paiement négociées (jours)",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("50")),
                        ],
                        verbose_name="Taux escompte obtenu (%)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "Franc CFA (CEMAC)"),
                            ("XOF", "Franc CFA (UEMOA)"),
                            ("EUR", "Euro"),
                            ("USD", "Dollar US"),
                        ],
                        default="XAF",
                        max_length=3,
                        verbose_name="Devise de transaction",
                    ),
                ),
                (
                    "incoterms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW - Ex Works"),
                            ("FCA", "FCA - Free Carrier"),
                            ("CPT", "CPT - Carriage Paid To"),
                            ("CIP", "CIP - Carriage Insurance Paid"),
                            ("DAT", "DAT - Delivered At Terminal"),
                            ("DAP", "DAP - Delivered At Place"),
                            ("DDP", "DDP - Delivered Duty Paid"),
                            ("FAS", "FAS - Free Alongside Ship"),
                            ("FOB", "FOB - Free On Board"),
                            ("CFR", "CFR - Cost And Freight"),
                            ("CIF", "CIF - Cost Insurance Freight"),
                        ],
                        max_length=10,
                        verbose_name="Incoterms appliqués",
                    ),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Virement bancaire"),
                            ("CHECK", "Chèque"),
                            ("CASH", "Espèces"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("COMPENSATION", "Compensation"),
                            ("OTHER", "Autre"),
                        ],
                        default="TRANSFER",
                        max_length=20,
                        verbose_name="Mode de règlement convenu",
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Seuil minimum de commande",
                    ),
                ),
                (
                    "maximum_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Plafond commande autorisé",
                    ),
                ),
                (
                    "has_framework_agreement",
                    models.BooleanField(
                        default=False, verbose_name="Accord cadre signé"
                    ),
                ),
                (
                    "framework_agreement_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence accord cadre",
                    ),
                ),
                (
                    "framework_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration accord"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="BIC/SWIFT"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Banque"),
                ),
                (
                    "bank_address",
                    models.TextField(blank=True, verbose_name="Adresse banque"),
                ),
                (
                    "supplier_rating",
                    models.CharField(
                        choices=[
                            ("A", "Excellent (A)"),
                            ("B", "Bon (B)"),
                            ("C", "Moyen (C)"),
                            ("D", "Faible (D)"),
                            ("E", "Non recommandé (E)"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Notation fournisseur (A/B/C/D/E)",
                    ),
                ),
                (
                    "current_outstanding",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=20,
                        verbose_name="Encours actuel",
                    ),
                ),
                (
                    "litigation_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nombre de litiges"
                    ),
                ),
                (
                    "service_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        editable=False,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Taux de service (%)",
                    ),
                ),
                (
                    "average_delivery_delay",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Délais moyens livraison (jours)",
                    ),
                ),
                (
                    "document_compliance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        editable=False,
                        max_digits=5,
                        verbose_name="Taux conformité documentaire (%)",
                    ),
                ),
                (
                    "iso_certifications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Certifications ISO"
                    ),
                ),
                (
                    "quality_certifications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Certifications qualité"
                    ),
                ),
                (
                    "other_approvals",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Autres agréments"
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score qualité (%)",
                    ),
                ),
                (
                    "delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score délais (%)",
                    ),
                ),
                (
                    "price_competitiveness",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Compétitivité prix (%)",
                    ),
                ),
                (
                    "overall_performance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Performance globale (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("QUALIFIED", "Qualifié"),
                            ("BLOCKED", "Bloqué"),
                            ("SUSPENDED", "Suspendu"),
                            ("ARCHIVED", "Archivé"),
                            ("PROSPECT", "Prospect"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "blocking_reason",
                    models.TextField(blank=True, verbose_name="Motif de blocage"),
                ),
                ("blocking_date", models.DateTimeField(blank=True, null=True)),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début contrat"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fin contrat"),
                ),
                (
                    "auto_renewal",
                    models.BooleanField(
                        default=False, verbose_name="Reconduction automatique"
                    ),
                ),
                (
                    "first_order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Première commande"
                    ),
                ),
                (
                    "last_order_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Dernière commande",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Dernier paiement",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Observations internes"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        limit_choices_to={
                            "account_class": "4",
                            "code__startswith": "40",
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="accounting.chartofaccounts",
                        verbose_name="Compte fournisseur (40x)",
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "suppliers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SupplierAnalytics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_orders_count", models.PositiveIntegerField(default=0)),
                ("total_invoices_count", models.PositiveIntegerField(default=0)),
                (
                    "total_amount_ordered",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "total_amount_invoiced",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "total_amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "average_delivery_time",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Temps livraison moyen (jours)",
                    ),
                ),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        max_digits=5,
                        verbose_name="Taux livraison à temps (%)",
                    ),
                ),
                (
                    "quality_defect_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Taux défauts qualité (%)",
                    ),
                ),
                (
                    "invoice_accuracy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        max_digits=5,
                        verbose_name="Taux justesse factures (%)",
                    ),
                ),
                (
                    "total_savings_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Économies escomptes",
                    ),
                ),
                (
                    "total_savings_negotiation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Économies négociation",
                    ),
                ),
                ("last_12m_orders", models.PositiveIntegerField(default=0)),
                (
                    "last_12m_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "average_order_frequency",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Fréquence commandes (jours)",
                    ),
                ),
                ("last_calculation", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics fournisseur",
                "verbose_name_plural": "Analytics fournisseurs",
                "db_table": "supplier_analytics",
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CEO", "Dirigeant"),
                            ("SALES", "Commercial"),
                            ("ACCOUNTANT", "Comptable"),
                            ("TECHNICAL", "Support technique"),
                            ("DELIVERY", "Livraison"),
                            ("QUALITY", "Qualité"),
                            ("LEGAL", "Juridique"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Service"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                (
                    "direct_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone direct"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "handles_orders",
                    models.BooleanField(
                        default=False, verbose_name="Gère les commandes"
                    ),
                ),
                (
                    "handles_invoices",
                    models.BooleanField(
                        default=False, verbose_name="Gère la facturation"
                    ),
                ),
                (
                    "handles_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Gère les livraisons"
                    ),
                ),
                (
                    "handles_quality",
                    models.BooleanField(default=False, verbose_name="Gère la qualité"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Contact principal"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact fournisseur",
                "verbose_name_plural": "Contacts fournisseurs",
                "db_table": "supplier_contacts",
            },
        ),
        migrations.CreateModel(
            name="SupplierDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("KBIS", "Extrait Kbis"),
                            ("RCCM", "RCCM"),
                            ("TAX_CERT", "Attestation fiscale"),
                            ("VAT_CERT", "Attestation TVA"),
                            ("INSURANCE", "Attestation assurance"),
                            ("BANK_CERT", "Attestation bancaire"),
                            ("ISO_CERT", "Certificat ISO"),
                            ("QUALITY_CERT", "Certificat qualité"),
                            ("CONTRACT", "Contrat"),
                            ("FRAMEWORK", "Accord cadre"),
                            ("CATALOG", "Catalogue produits"),
                            ("PRICE_LIST", "Liste prix"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=20)),
                ("document_date", models.DateField(verbose_name="Date document")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date expiration"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="Numéro"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "alert_before_expiry",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Alerte X jours avant expiration"
                    ),
                ),
                ("is_expired", models.BooleanField(default=False, editable=False)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document fournisseur",
                "verbose_name_plural": "Documents fournisseurs",
                "db_table": "supplier_documents",
                "ordering": ["-document_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierEvaluation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("QUARTERLY", "Trimestrielle"),
                            ("ANNUAL", "Annuelle"),
                            ("PROJECT", "Projet spécifique"),
                            ("INCIDENT", "Suite à incident"),
                            ("AUDIT", "Audit qualité"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "evaluation_period_start",
                    models.DateField(verbose_name="Début période"),
                ),
                ("evaluation_period_end", models.DateField(verbose_name="Fin période")),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score qualité (%)",
                    ),
                ),
                (
                    "delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score délais (%)",
                    ),
                ),
                (
                    "service_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score service (%)",
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score compétitivité prix (%)",
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score conformité (%)",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Score global (%)",
                    ),
                ),
                (
                    "strengths",
                    models.TextField(blank=True, verbose_name="Points forts"),
                ),
                (
                    "weaknesses",
                    models.TextField(blank=True, verbose_name="Points d'amélioration"),
                ),
                (
                    "action_plan",
                    models.TextField(blank=True, verbose_name="Plan d'action"),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("CONTINUE", "Continuer collaboration"),
                            ("DEVELOP", "Développer partenariat"),
                            ("MONITOR", "Surveiller performance"),
                            ("REDUCE", "Réduire collaboration"),
                            ("TERMINATE", "Arrêter collaboration"),
                        ],
                        max_length=20,
                        verbose_name="Recommandation",
                    ),
                ),
                ("evaluation_date", models.DateField(default=datetime.date.today)),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation fournisseur",
                "verbose_name_plural": "Évaluations fournisseurs",
                "db_table": "supplier_evaluations",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Numéro facture"),
                ),
                ("invoice_date", models.DateField(verbose_name="Date facture")),
                ("due_date", models.DateField(verbose_name="Date échéance")),
                (
                    "amount_excl_tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant HT"
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant TVA"
                    ),
                ),
                (
                    "amount_incl_tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant TTC"
                    ),
                ),
                (
                    "purchase_order_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence bon de commande",
                    ),
                ),
                (
                    "delivery_receipt_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence bon de livraison",
                    ),
                ),
                (
                    "wise_procure_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Wise Procure"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Reçue"),
                            ("VALIDATED", "Validée technique"),
                            ("ACCOUNTING_OK", "Validée comptable"),
                            ("APPROVED", "Approuvée paiement"),
                            ("PAID", "Payée"),
                            ("DISPUTED", "Contestée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "technical_validation",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                            ("REQUIRES_INFO", "Info demandée"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "technical_validation_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("technical_comments", models.TextField(blank=True)),
                (
                    "accounting_validation",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                            ("REQUIRES_INFO", "Info demandée"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "accounting_validation_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("accounting_comments", models.TextField(blank=True)),
                ("ocr_extracted_data", models.JSONField(blank=True, default=dict)),
                (
                    "ocr_confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Score confiance OCR (%)",
                    ),
                ),
                (
                    "duplicate_check_passed",
                    models.BooleanField(default=True, verbose_name="Pas de doublon"),
                ),
                (
                    "amount_check_passed",
                    models.BooleanField(default=True, verbose_name="Montant cohérent"),
                ),
                (
                    "po_match_passed",
                    models.BooleanField(default=True, verbose_name="Correspondance BC"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date paiement"
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence paiement"
                    ),
                ),
                (
                    "accounting_validator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "technical_validator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="technical_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture fournisseur",
                "verbose_name_plural": "Factures fournisseurs",
                "db_table": "supplier_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_reference", models.CharField(max_length=100, unique=True)),
                ("payment_date", models.DateField(verbose_name="Date paiement")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant brut"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Montant escompte",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant net"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Paiement standard"),
                            ("EARLY_DISCOUNT", "Paiement anticipé avec escompte"),
                            ("GROUPED", "Paiement groupé"),
                            ("PARTIAL", "Paiement partiel"),
                            ("COMPENSATION", "Compensation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "early_payment_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jours d'anticipation"
                    ),
                ),
                (
                    "discount_rate_applied",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Taux escompte appliqué (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposé"),
                            ("APPROVED", "Approuvé"),
                            ("EXECUTED", "Exécuté"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("bank_transaction_id", models.CharField(blank=True, max_length=100)),
                ("execution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_invoices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="payments",
                        to="suppliers.supplierinvoice",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement fournisseur",
                "verbose_name_plural": "Paiements fournisseurs",
                "db_table": "supplier_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["company", "supplier_type"], name="suppliers_company_8b4b97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["company", "status"], name="suppliers_company_825b6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["legal_name"], name="suppliers_legal_n_8d77f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["supplier_rating"], name="suppliers_supplie_81614a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["overall_performance"], name="suppliers_overall_2b9c12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["-last_order_date"], name="suppliers_last_or_e5a98c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="supplierdocument",
            index=models.Index(
                fields=["supplier", "document_type"],
                name="supplier_do_supplie_58e92c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierdocument",
            index=models.Index(
                fields=["-expiry_date"], name="supplier_do_expiry__553046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["supplier", "status"], name="supplier_in_supplie_9114e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["-invoice_date"], name="supplier_in_invoice_7dc1ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["-due_date"], name="supplier_in_due_dat_3c0f34_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplierinvoice",
            unique_together={("supplier", "invoice_number")},
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["supplier", "status"], name="supplier_pa_supplie_7b3476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["-payment_date"], name="supplier_pa_payment_a12b28_idx"
            ),
        ),
    ]
