# Generated by Django 5.2.4 on 2025-10-19 12:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de la banque"),
                ),
                (
                    "short_name",
                    models.CharField(max_length=50, verbose_name="Nom court"),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("COMMERCIAL", "Banque commerciale"),
                            ("INVESTMENT", "Banque d'investissement"),
                            ("MICROFINANCE", "Institution de microfinance"),
                            ("COOPERATIVE", "Banque coopérative"),
                            ("CENTRAL", "Banque centrale"),
                            ("OTHER", "Autre"),
                        ],
                        default="COMMERCIAL",
                        max_length=20,
                    ),
                ),
                (
                    "bic_code",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="Code BIC"
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="Code SWIFT"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro agrément"
                    ),
                ),
                ("address", models.TextField(verbose_name="Adresse")),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "supports_psd2",
                    models.BooleanField(default=False, verbose_name="Support PSD2"),
                ),
                (
                    "supports_ebics",
                    models.BooleanField(default=False, verbose_name="Support EBICS"),
                ),
                (
                    "supports_swift",
                    models.BooleanField(default=False, verbose_name="Support SWIFT"),
                ),
                (
                    "supports_iso20022",
                    models.BooleanField(
                        default=False, verbose_name="Support ISO 20022"
                    ),
                ),
                (
                    "supports_gimac",
                    models.BooleanField(
                        default=False, verbose_name="Support GIMAC (CEMAC)"
                    ),
                ),
                (
                    "supports_sica_uemoa",
                    models.BooleanField(
                        default=False, verbose_name="Support SICA-UEMOA"
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(blank=True, verbose_name="Point d'accès API"),
                ),
                ("api_version", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Banque",
                "verbose_name_plural": "Banques",
                "db_table": "treasury_banks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Numéro de compte"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Compte courant"),
                            ("SAVINGS", "Compte épargne"),
                            ("TERM_DEPOSIT", "Dépôt à terme"),
                            ("CREDIT_LINE", "Ligne de crédit"),
                            ("FOREIGN_CURRENCY", "Compte devise"),
                            ("OTHER", "Autre"),
                        ],
                        default="CHECKING",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "Franc CFA (CEMAC)"),
                            ("XOF", "Franc CFA (UEMOA)"),
                            ("EUR", "Euro"),
                            ("USD", "Dollar US"),
                        ],
                        default="XAF",
                        max_length=3,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=20,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Solde minimum",
                    ),
                ),
                (
                    "overdraft_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Autorisation découvert",
                    ),
                ),
                (
                    "daily_transfer_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Plafond virement quotidien",
                    ),
                ),
                (
                    "daily_withdrawal_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Plafond retrait quotidien",
                    ),
                ),
                (
                    "account_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Frais de tenue de compte",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Taux d'intérêt créditeur",
                    ),
                ),
                (
                    "overdraft_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Taux découvert",
                    ),
                ),
                ("opening_date", models.DateField(verbose_name="Date d'ouverture")),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                (
                    "last_sync_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                (
                    "auto_reconciliation",
                    models.BooleanField(
                        default=False, verbose_name="Rapprochement automatique"
                    ),
                ),
                (
                    "reconciliation_tolerance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.01"),
                        max_digits=10,
                        verbose_name="Tolérance rapprochement",
                    ),
                ),
                (
                    "bank_identifier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Identifiant banque"
                    ),
                ),
                (
                    "connection_settings",
                    models.JSONField(default=dict, verbose_name="Paramètres connexion"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("SUSPENDED", "Suspendu"),
                            ("CLOSED", "Clôturé"),
                            ("BLOCKED", "Bloqué"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "is_main_account",
                    models.BooleanField(default=False, verbose_name="Compte principal"),
                ),
                (
                    "accounting_account",
                    models.ForeignKey(
                        limit_choices_to={
                            "account_class": "5",
                            "code__startswith": "52",
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="treasury.bank",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte bancaire",
                "verbose_name_plural": "Comptes bancaires",
                "db_table": "treasury_bank_accounts",
                "ordering": ["bank__name", "account_number"],
            },
        ),
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connection_name",
                    models.CharField(max_length=100, verbose_name="Nom connexion"),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("SWIFT_MT940", "SWIFT MT940/942"),
                            ("SWIFT_MT101", "SWIFT MT101/103"),
                            ("EBICS_T", "EBICS T/TS"),
                            ("EBICS_A", "EBICS A/E/H"),
                            ("PSD2_AISP", "PSD2 AISP"),
                            ("PSD2_PISP", "PSD2 PISP"),
                            ("ISO20022_CAMT", "ISO 20022 CAMT"),
                            ("ISO20022_PAIN", "ISO 20022 PAIN"),
                            ("GIMAC", "GIMAC (Zone CEMAC)"),
                            ("SICA_UEMOA", "SICA-UEMOA"),
                            ("LOCAL_API", "API bancaire locale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint_url", models.URLField(verbose_name="URL point d'accès")),
                (
                    "user_id",
                    models.CharField(
                        max_length=100, verbose_name="Identifiant utilisateur"
                    ),
                ),
                (
                    "partner_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID partenaire"
                    ),
                ),
                (
                    "client_certificate",
                    models.TextField(blank=True, verbose_name="Certificat client"),
                ),
                (
                    "bank_certificate",
                    models.TextField(blank=True, verbose_name="Certificat banque"),
                ),
                (
                    "encryption_key",
                    models.TextField(blank=True, verbose_name="Clé de chiffrement"),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(default=True, verbose_name="Sync automatique"),
                ),
                (
                    "sync_frequency_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Fréquence sync (minutes)"
                    ),
                ),
                (
                    "can_retrieve_statements",
                    models.BooleanField(
                        default=True, verbose_name="Récupération relevés"
                    ),
                ),
                (
                    "can_initiate_payments",
                    models.BooleanField(
                        default=False, verbose_name="Initiation virements"
                    ),
                ),
                (
                    "can_get_realtime_status",
                    models.BooleanField(
                        default=False, verbose_name="Statut temps réel"
                    ),
                ),
                (
                    "can_manage_mandates",
                    models.BooleanField(default=False, verbose_name="Gestion mandats"),
                ),
                (
                    "can_download_documents",
                    models.BooleanField(
                        default=True, verbose_name="Téléchargement docs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ERROR", "Erreur"),
                            ("MAINTENANCE", "Maintenance"),
                            ("EXPIRED", "Expirée"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                ("last_successful_sync", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("average_response_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=5
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="treasury.bankaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connexion bancaire",
                "verbose_name_plural": "Connexions bancaires",
                "db_table": "treasury_bank_connections",
            },
        ),
        migrations.CreateModel(
            name="CashFlowForecast",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Quotidienne"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("MONTHLY", "Mensuelle"),
                            ("SCENARIO", "Scénario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("OPTIMISTIC", "Optimiste"),
                            ("REALISTIC", "Réaliste"),
                            ("PESSIMISTIC", "Pessimiste"),
                            ("STRESS_TEST", "Test de stress"),
                        ],
                        default="REALISTIC",
                        max_length=20,
                    ),
                ),
                ("forecast_date", models.DateField(verbose_name="Date de prévision")),
                ("period_start", models.DateField(verbose_name="Début période")),
                ("period_end", models.DateField(verbose_name="Fin période")),
                (
                    "expected_receivables",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Encaissements prévus",
                    ),
                ),
                (
                    "receivables_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Confiance encaissements (%)",
                    ),
                ),
                (
                    "expected_payables",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Décaissements prévus",
                    ),
                ),
                (
                    "payables_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Confiance décaissements (%)",
                    ),
                ),
                (
                    "other_inflows",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Autres entrées",
                    ),
                ),
                (
                    "other_outflows",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Autres sorties",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Solde d'ouverture",
                    ),
                ),
                (
                    "projected_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Solde projeté"
                    ),
                ),
                (
                    "net_cash_flow",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Cash flow net"
                    ),
                ),
                (
                    "liquidity_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Ratio de liquidité",
                    ),
                ),
                (
                    "coverage_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jours de couverture"
                    ),
                ),
                ("ml_model_version", models.CharField(blank=True, max_length=20)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Score confiance global",
                    ),
                ),
                (
                    "calculation_time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Temps calcul (ms)"
                    ),
                ),
                (
                    "detailed_forecast",
                    models.JSONField(default=dict, verbose_name="Prévision détaillée"),
                ),
                (
                    "assumptions",
                    models.JSONField(default=dict, verbose_name="Hypothèses"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_forecasts",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prévision de trésorerie",
                "verbose_name_plural": "Prévisions de trésorerie",
                "db_table": "treasury_cash_flow_forecasts",
                "ordering": ["-forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="FundCall",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "call_reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence appel"
                    ),
                ),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("INTER_ACCOUNT", "Transfert inter-comptes"),
                            ("CREDIT_LINE", "Activation ligne de crédit"),
                            ("OVERDRAFT", "Demande de découvert"),
                            ("EMERGENCY", "Transfert d'urgence"),
                            ("LIQUIDITY", "Apport de liquidité"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "justification_type",
                    models.CharField(
                        choices=[
                            ("SUPPLIER_PAYMENTS", "Paiement fournisseurs"),
                            ("PAYROLL", "Paiement salaires"),
                            ("TAX_PAYMENTS", "Paiements fiscaux/sociaux"),
                            ("LOAN_REPAYMENT", "Remboursement emprunts"),
                            ("INVESTMENT", "Investissement"),
                            ("WORKING_CAPITAL", "Besoin en fonds de roulement"),
                            ("EMERGENCY", "Urgence opérationnelle"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "business_justification",
                    models.TextField(verbose_name="Justification du transfert"),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Élevée"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant demandé"
                    ),
                ),
                (
                    "amount_transferred",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=20,
                        verbose_name="Montant transféré",
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now_add=True, verbose_name="Date de demande"),
                ),
                ("needed_date", models.DateField(verbose_name="Date de besoin")),
                (
                    "execution_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'exécution"
                    ),
                ),
                (
                    "transfer_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Frais de transfert",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING_APPROVAL", "Attente validation"),
                            ("APPROVED", "Approuvé"),
                            ("INITIATED", "Initié"),
                            ("IN_TRANSIT", "En transit"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_transfer_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence du virement bancaire",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fund_calls_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_calls",
                        to="core.societe",
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_calls_destination",
                        to="treasury.bankaccount",
                        verbose_name="Compte destination (qui reçoit les fonds)",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fund_calls_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_calls_source",
                        to="treasury.bankaccount",
                        verbose_name="Compte source (qui donne les fonds)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appel de fonds",
                "verbose_name_plural": "Appels de fonds",
                "db_table": "treasury_fund_calls",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="InterBankTransfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contributor_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom du contributeur"
                    ),
                ),
                (
                    "contributor_type",
                    models.CharField(
                        choices=[
                            ("SHAREHOLDER", "Actionnaire"),
                            ("PARTNER", "Associé"),
                            ("PARENT_COMPANY", "Société mère"),
                            ("SUBSIDIARY", "Filiale"),
                            ("GROUP_ENTITY", "Entité du groupe"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "contributor_code",
                    models.CharField(max_length=50, verbose_name="Code contributeur"),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Pourcentage de participation",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant alloué"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Montant payé",
                    ),
                ),
                ("notification_date", models.DateTimeField(blank=True, null=True)),
                ("commitment_date", models.DateTimeField(blank=True, null=True)),
                ("expected_payment_date", models.DateField(blank=True, null=True)),
                ("actual_payment_date", models.DateField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOTIFIED", "Notifié"),
                            ("ACKNOWLEDGED", "Accusé réception"),
                            ("COMMITTED", "Engagement reçu"),
                            ("PARTIALLY_PAID", "Partiellement payé"),
                            ("FULLY_PAID", "Entièrement payé"),
                            ("REFUSED", "Refusé"),
                            ("OVERDUE", "En retard"),
                        ],
                        default="NOTIFIED",
                        max_length=30,
                    ),
                ),
                (
                    "reminder_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "last_reminder_date",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "payment_iban",
                    models.CharField(
                        blank=True, max_length=34, verbose_name="IBAN de versement"
                    ),
                ),
                (
                    "payment_reference_code",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "fund_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="treasury.fundcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributeur appel de fonds",
                "verbose_name_plural": "Contributeurs appels de fonds",
                "db_table": "treasury_fund_call_contributors",
                "ordering": ["-ownership_percentage"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("SEPA_TRANSFER", "Virement SEPA"),
                            ("SWIFT_TRANSFER", "Virement SWIFT"),
                            ("LOCAL_TRANSFER", "Virement local (CEMAC/UEMOA)"),
                            ("SUPPLIER_DEBIT", "Prélèvement fournisseur"),
                            ("CHECK", "Chèque"),
                            ("BUSINESS_CARD", "Carte affaires"),
                            ("CASH", "Espèces"),
                            ("INCOMING_TRANSFER", "Virement reçu"),
                            ("DIRECT_DEBIT", "Prélèvement émis"),
                            ("CHECK_RECEIVED", "Chèque reçu"),
                            ("CASH_RECEIVED", "Espèces reçues"),
                            ("CARD_PAYMENT", "Paiement carte"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CUSTOMER_OFFSET", "Compensation client"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Entrant"), ("OUTBOUND", "Sortant")],
                        max_length=10,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence paiement"
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence externe"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(default="XAF", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "amount_in_base_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Montant en devise de base",
                    ),
                ),
                ("value_date", models.DateField(verbose_name="Date de valeur")),
                (
                    "execution_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'exécution"
                    ),
                ),
                (
                    "confirmation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date confirmation"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "beneficiary_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom bénéficiaire"
                    ),
                ),
                (
                    "beneficiary_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Compte bénéficiaire"
                    ),
                ),
                (
                    "beneficiary_bank",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Banque bénéficiaire"
                    ),
                ),
                (
                    "required_signatures",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Signatures requises"
                    ),
                ),
                (
                    "current_signatures",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Signatures obtenues"
                    ),
                ),
                (
                    "approval_workflow",
                    models.JSONField(
                        default=list, verbose_name="Workflow d'approbation"
                    ),
                ),
                ("current_approval_step", models.PositiveIntegerField(default=0)),
                (
                    "requires_mfa",
                    models.BooleanField(
                        default=False, verbose_name="Double authentification requise"
                    ),
                ),
                (
                    "ip_restriction",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Restriction IP"
                    ),
                ),
                (
                    "user_limit_checked",
                    models.BooleanField(
                        default=True, verbose_name="Plafond utilisateur vérifié"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING_APPROVAL", "En attente approbation"),
                            ("APPROVED", "Approuvé"),
                            ("EXECUTED", "Exécuté"),
                            ("CONFIRMED", "Confirmé par banque"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "bank_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Frais bancaires",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="treasury.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.societe",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasury_payments",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "treasury_payments",
                "ordering": ["-value_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_PAYMENT", "Paiement client"),
                            ("LOAN_RECEIPT", "Réception prêt"),
                            ("FUND_CALL_RECEIPT", "Réception appel de fonds"),
                            ("INVESTMENT_INCOME", "Revenus placement"),
                            ("OTHER_INCOME", "Autres recettes"),
                            ("SUPPLIER_PAYMENT", "Paiement fournisseur"),
                            ("PAYROLL", "Paiement salaires"),
                            ("TAX_PAYMENT", "Paiement taxes"),
                            ("LOAN_REPAYMENT", "Remboursement prêt"),
                            ("INVESTMENT", "Investissement"),
                            ("OTHER_EXPENSE", "Autres dépenses"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INFLOW", "Entrée"), ("OUTFLOW", "Sortie")],
                        max_length=10,
                    ),
                ),
                (
                    "movement_reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence mouvement"
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence externe"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant"
                    ),
                ),
                ("currency", models.CharField(default="XAF", max_length=3)),
                ("scheduled_date", models.DateField(verbose_name="Date programmée")),
                ("value_date", models.DateField(verbose_name="Date de valeur")),
                (
                    "execution_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'exécution"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "counterpart_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contrepartie"
                    ),
                ),
                (
                    "counterpart_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Compte contrepartie"
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programmé"),
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("EXECUTED", "Exécuté"),
                            ("CONFIRMED", "Confirmé"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Solde avant",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Solde après",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_movements",
                        to="treasury.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_movements",
                        to="core.societe",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "related_fund_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="treasury.fundcall",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="treasury.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de trésorerie",
                "verbose_name_plural": "Mouvements de trésorerie",
                "db_table": "treasury_cash_movements",
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreasuryAlert",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LOW_BALANCE", "Solde faible"),
                            ("OVERDRAFT", "Découvert"),
                            ("PAYMENT_DUE", "Échéance paiement"),
                            ("FUND_CALL_NEEDED", "Appel de fonds requis"),
                            ("CURRENCY_EXPOSURE", "Exposition devises"),
                            ("LIMIT_EXCEEDED", "Limite dépassée"),
                            ("FORECAST_NEGATIVE", "Prévision négative"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                            ("CRITICAL", "Critique"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("auto_actions_triggered", models.JSONField(default=list)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasury_alerts",
                        to="core.societe",
                    ),
                ),
                (
                    "related_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.bankaccount",
                    ),
                ),
                (
                    "related_fund_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.fundcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte trésorerie",
                "verbose_name_plural": "Alertes trésorerie",
                "db_table": "treasury_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreasuryPosition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_date", models.DateField(verbose_name="Date position")),
                (
                    "position_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Heure calcul"
                    ),
                ),
                (
                    "opening_balance_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Solde début total",
                    ),
                ),
                (
                    "inflows_today",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Encaissements du jour",
                    ),
                ),
                (
                    "outflows_today",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Décaissements du jour",
                    ),
                ),
                (
                    "current_balance_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Solde actuel total",
                    ),
                ),
                (
                    "total_credit_lines",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Lignes crédit disponibles",
                    ),
                ),
                (
                    "forecast_7d_inflows",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Encaissements 7j"
                    ),
                ),
                (
                    "forecast_7d_outflows",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Décaissements 7j"
                    ),
                ),
                (
                    "forecast_7d_position",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Position 7j"
                    ),
                ),
                (
                    "liquidity_needs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Besoins de liquidité",
                    ),
                ),
                (
                    "liquidity_surplus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Excédent de liquidité",
                    ),
                ),
                (
                    "currency_breakdown",
                    models.JSONField(default=dict, verbose_name="Répartition devises"),
                ),
                (
                    "alerts_generated",
                    models.JSONField(default=list, verbose_name="Alertes générées"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasury_positions",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position de trésorerie",
                "verbose_name_plural": "Positions de trésorerie",
                "db_table": "treasury_positions",
                "ordering": ["-position_date", "-position_time"],
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["company", "status"], name="treasury_ba_company_1e987c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["bank", "account_number"], name="treasury_ba_bank_id_d7f032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["iban"], name="treasury_ba_iban_2b2855_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["-current_balance"], name="treasury_ba_current_bcc565_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("company", "account_number", "bank")},
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(
                fields=["bank_account", "status"], name="treasury_ba_bank_ac_77baed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(
                fields=["-last_successful_sync"], name="treasury_ba_last_su_454df5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankconnection",
            unique_together={("bank_account", "protocol")},
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["company", "-forecast_date"],
                name="treasury_ca_company_69e28f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["forecast_type", "scenario_type"],
                name="treasury_ca_forecas_210bf5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cashflowforecast",
            unique_together={
                ("company", "forecast_date", "forecast_type", "scenario_type")
            },
        ),
        migrations.AddIndex(
            model_name="fundcall",
            index=models.Index(
                fields=["company", "status"], name="treasury_fu_company_b977b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundcall",
            index=models.Index(
                fields=["-request_date"], name="treasury_fu_request_90e177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundcall",
            index=models.Index(
                fields=["urgency_level", "needed_date"],
                name="treasury_fu_urgency_d86cac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interbanktransfer",
            index=models.Index(
                fields=["fund_call", "status"], name="treasury_fu_fund_ca_7944f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interbanktransfer",
            index=models.Index(
                fields=["-notification_date"], name="treasury_fu_notific_bff2c6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interbanktransfer",
            unique_together={("fund_call", "contributor_code")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["company", "direction", "status"],
                name="treasury_pa_company_6d9c03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["bank_account", "-value_date"],
                name="treasury_pa_bank_ac_536063_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_reference"], name="treasury_pa_payment_6b37d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-execution_date"], name="treasury_pa_executi_093e67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["company", "direction", "-scheduled_date"],
                name="treasury_ca_company_e89656_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["bank_account", "-value_date"],
                name="treasury_ca_bank_ac_d42c08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["movement_type", "execution_status"],
                name="treasury_ca_movemen_46b0d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["-execution_date"], name="treasury_ca_executi_50a88c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryalert",
            index=models.Index(
                fields=["company", "severity", "-created_at"],
                name="treasury_al_company_900322_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryalert",
            index=models.Index(
                fields=["alert_type", "is_resolved"],
                name="treasury_al_alert_t_af5870_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryposition",
            index=models.Index(
                fields=["company", "-position_date"],
                name="treasury_po_company_e85e4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treasuryposition",
            index=models.Index(
                fields=["-position_time"], name="treasury_po_positio_fb6e5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="treasuryposition",
            unique_together={("company", "position_date")},
        ),
    ]
