# Generated by Django 5.2.4 on 2025-10-23 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcall",
            name="destination_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fund_calls_destination",
                to="treasury.bankaccount",
                verbose_name="Compte destination (qui reçoit les fonds)",
            ),
        ),
        migrations.AlterField(
            model_name="fundcall",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fund_calls_source",
                to="treasury.bankaccount",
                verbose_name="Compte source (qui donne les fonds)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="beneficiary_account",
            field=models.CharField(
                blank=True,
                help_text="Format IBAN requis (ex: FR7612345678901234567890123)",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format IBAN invalide. Format attendu: 2 lettres pays + 2 chiffres clé + max 30 caractères alphanumériques",
                        regex="^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$",
                    )
                ],
                verbose_name="Compte bénéficiaire (IBAN)",
            ),
        ),
    ]
