# Generated by Django 5.2.8 on 2025-11-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0002_alter_fundcall_destination_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcall",
            name="destination_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fund_calls_destination",
                to="treasury.bankaccount",
                verbose_name="Compte destination (qui reçoit les fonds)",
            ),
        ),
        migrations.AlterField(
            model_name="fundcall",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fund_calls_source",
                to="treasury.bankaccount",
                verbose_name="Compte source (qui donne les fonds)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="beneficiary_account",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Compte bénéficiaire"
            ),
        ),
    ]
