# Generated by Django 4.2.7 on 2025-10-08 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("manager", "Manager"),
                            ("comptable", "Comptable"),
                            ("controller", "Contrôleur"),
                            ("viewer", "Visualiseur"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="Briefcase", max_length=50)),
                ("color", models.CharField(default="#6A8A82", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "db_table": "workspaces",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceQuickAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="Zap", max_length=50)),
                ("color", models.CharField(default="#6A8A82", max_length=7)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("navigate", "Navigation"),
                            ("modal", "Ouvrir modal"),
                            ("api_call", "Appel API"),
                            ("external", "Lien externe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_target", models.CharField(max_length=255)),
                ("required_permission", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("show_badge", models.BooleanField(default=False)),
                ("badge_api_endpoint", models.CharField(blank=True, max_length=255)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_actions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Rapide Workspace",
                "verbose_name_plural": "Actions Rapides Workspace",
                "db_table": "workspace_quick_actions",
                "ordering": ["workspace", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserWorkspacePreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hidden_widgets", models.JSONField(blank=True, default=list)),
                ("custom_widget_order", models.JSONField(blank=True, default=dict)),
                ("custom_layout", models.JSONField(blank=True, default=dict)),
                ("show_welcome_message", models.BooleanField(default=True)),
                ("compact_mode", models.BooleanField(default=False)),
                (
                    "default_workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_default",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence Workspace Utilisateur",
                "verbose_name_plural": "Préférences Workspace Utilisateur",
                "db_table": "user_workspace_preferences",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceWidget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("stat", "Statistique"),
                            ("chart", "Graphique"),
                            ("list", "Liste"),
                            ("action", "Action rapide"),
                            ("link", "Lien rapide"),
                            ("notification", "Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="Square", max_length=50)),
                ("color", models.CharField(default="#6A8A82", max_length=7)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("api_endpoint", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=1)),
                ("height", models.IntegerField(default=1)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget Workspace",
                "verbose_name_plural": "Widgets Workspace",
                "db_table": "workspace_widgets",
                "ordering": ["workspace", "order"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "order"],
                        name="workspace_w_workspa_871054_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceStatistic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stat_key", models.CharField(db_index=True, max_length=100)),
                ("stat_label", models.CharField(max_length=100)),
                ("stat_value", models.CharField(max_length=255)),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("number", "Nombre"),
                            ("currency", "Montant"),
                            ("percentage", "Pourcentage"),
                            ("text", "Texte"),
                        ],
                        default="number",
                        max_length=20,
                    ),
                ),
                (
                    "trend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("up", "Hausse"),
                            ("down", "Baisse"),
                            ("stable", "Stable"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("target_value", models.CharField(blank=True, max_length=255)),
                ("progress", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("cache_duration", models.IntegerField(default=300)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique Workspace",
                "verbose_name_plural": "Statistiques Workspace",
                "db_table": "workspace_statistics",
                "indexes": [
                    models.Index(
                        fields=["workspace", "stat_key"],
                        name="workspace_s_workspa_bcaae4_idx",
                    ),
                    models.Index(
                        fields=["last_calculated"],
                        name="workspace_s_last_ca_c82eff_idx",
                    ),
                ],
                "unique_together": {("workspace", "stat_key")},
            },
        ),
    ]
