# Generated by Django 5.2.4 on 2025-10-19 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AxeAnalytique",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type_axe",
                    models.CharField(
                        choices=[
                            ("ACTIVITE", "Activité/Division"),
                            ("CENTRE_COUT", "Centre de coûts"),
                            ("CENTRE_PROFIT", "Centre de profit"),
                            ("PROJET", "Projet"),
                            ("PRODUIT", "Produit/Service"),
                            ("CLIENT", "Client"),
                            ("GEOGRAPHIE", "Zone géographique"),
                            ("RESPONSABLE", "Responsable"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(
                        default=False, help_text="Ventilation obligatoire pour cet axe"
                    ),
                ),
                (
                    "ventilation_totale",
                    models.BooleanField(
                        default=True, help_text="Ventilation à 100% obligatoire"
                    ),
                ),
                ("hierarchique", models.BooleanField(default=False)),
                ("profondeur_max", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                (
                    "couleur",
                    models.CharField(
                        default="#007bff",
                        help_text="Couleur d'affichage (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "comptes_concernes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Comptes pour lesquels cet axe est obligatoire",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axes_analytiques",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Axe analytique",
                "verbose_name_plural": "Axes analytiques",
                "db_table": "analytics_axe",
                "ordering": ["ordre_affichage", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="CleRepartition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "coefficients",
                    models.JSONField(
                        default=dict,
                        help_text="Coefficients par section: {section_code: coefficient}",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cles_repartition",
                        to="analytics.axeanalytique",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cles_repartition",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé de répartition",
                "verbose_name_plural": "Clés de répartition",
                "db_table": "analytics_cle_repartition",
            },
        ),
        migrations.CreateModel(
            name="ModeleVentilation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ventilations_defaut",
                    models.JSONField(
                        default=dict,
                        help_text="Structure: {axe_code: [{section_code: pourcentage}]}",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions pour l'application automatique",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles_ventilation",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles_ventilation",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de ventilation",
                "verbose_name_plural": "Modèles de ventilation",
                "db_table": "analytics_modele_ventilation",
            },
        ),
        migrations.CreateModel(
            name="RepartitionAutomatique",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type_repartition",
                    models.CharField(
                        choices=[
                            ("FIXE", "Pourcentage fixe"),
                            ("PRORATA", "Prorata d'une base"),
                            ("CLE_REPARTITION", "Clé de répartition"),
                            ("HISTORIQUE", "Basé sur l'historique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("MENSUELLE", "Mensuelle"),
                            ("TRIMESTRIELLE", "Trimestrielle"),
                            ("SEMESTRIELLE", "Semestrielle"),
                            ("ANNUELLE", "Annuelle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parametres", models.JSONField(blank=True, default=dict)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("derniere_execution", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("execution_auto", models.BooleanField(default=False)),
                (
                    "compte_base",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte de base pour le prorata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "compte_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repartitions_source",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repartitions_auto",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Répartition automatique",
                "verbose_name_plural": "Répartitions automatiques",
                "db_table": "analytics_repartition_auto",
            },
        ),
        migrations.CreateModel(
            name="LigneRepartition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "montant_fixe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant fixe (si applicable)",
                        max_digits=15,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "repartition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="analytics.repartitionautomatique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de répartition",
                "verbose_name_plural": "Lignes de répartition",
                "db_table": "analytics_ligne_repartition",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="SectionAnalytique",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "budgetaire",
                    models.BooleanField(default=False, help_text="Section avec budget"),
                ),
                (
                    "budget_annuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Budget annuel de la section",
                        max_digits=15,
                    ),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "coefficients_repartition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Coefficients pour la répartition automatique",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("couleur", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="analytics.axeanalytique",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="analytics.sectionanalytique",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section analytique",
                "verbose_name_plural": "Sections analytiques",
                "db_table": "analytics_section",
                "ordering": ["ordre_affichage", "libelle"],
            },
        ),
        migrations.AddField(
            model_name="repartitionautomatique",
            name="sections_destination",
            field=models.ManyToManyField(
                through="analytics.LigneRepartition", to="analytics.sectionanalytique"
            ),
        ),
        migrations.AddField(
            model_name="lignerepartition",
            name="section_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.sectionanalytique",
            ),
        ),
        migrations.CreateModel(
            name="BalanceAnalytique",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exercice", models.IntegerField()),
                ("periode", models.CharField(help_text="Format YYYY-MM", max_length=7)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "solde_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "mouvement_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "mouvement_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "solde_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "type_solde",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Solde débiteur"),
                            ("CREDIT", "Solde créditeur"),
                            ("EQUILIBRE", "Équilibré"),
                        ],
                        default="EQUILIBRE",
                        max_length=10,
                    ),
                ),
                ("nb_mouvements", models.IntegerField(default=0)),
                ("date_calcul", models.DateTimeField(auto_now=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances_analytiques",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances_analytiques",
                        to="core.societe",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="analytics.sectionanalytique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance analytique",
                "verbose_name_plural": "Balances analytiques",
                "db_table": "analytics_balance",
                "ordering": ["-periode", "section__code", "compte__code"],
            },
        ),
        migrations.CreateModel(
            name="TableauBord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="Configuration des widgets et filtres"
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("favori", models.BooleanField(default=False)),
                (
                    "axes_analyses",
                    models.ManyToManyField(blank=True, to="analytics.axeanalytique"),
                ),
                (
                    "societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tableaux_bord",
                        to="core.societe",
                    ),
                ),
                (
                    "utilisateurs_autorises",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Tableau de bord",
                "verbose_name_plural": "Tableaux de bord",
                "db_table": "analytics_tableau_bord",
            },
        ),
        migrations.CreateModel(
            name="VentilationAnalytique",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=200, null=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ligne_ecriture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventilations",
                        to="accounting.journalentryline",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventilations",
                        to="analytics.sectionanalytique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ventilation analytique",
                "verbose_name_plural": "Ventilations analytiques",
                "db_table": "analytics_ventilation",
            },
        ),
        migrations.CreateModel(
            name="WidgetTableauBord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "type_graphique",
                    models.CharField(
                        choices=[
                            ("BAR", "Barres"),
                            ("LINE", "Lignes"),
                            ("PIE", "Secteurs"),
                            ("AREA", "Aires"),
                            ("SCATTER", "Nuage de points"),
                            ("TABLE", "Tableau"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requete",
                    models.JSONField(
                        help_text="Configuration de la requête de données"
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("largeur", models.IntegerField(default=6)),
                ("hauteur", models.IntegerField(default=4)),
                ("couleurs", models.JSONField(blank=True, default=list)),
                ("options_graphique", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tableau_bord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="analytics.tableaubord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgets",
                "db_table": "analytics_widget",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.AddIndex(
            model_name="axeanalytique",
            index=models.Index(
                fields=["societe", "type_axe"], name="analytics_a_societe_4f1a84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="axeanalytique",
            index=models.Index(
                fields=["ordre_affichage"], name="analytics_a_ordre_a_9392c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="axeanalytique",
            unique_together={("societe", "code")},
        ),
        migrations.AddIndex(
            model_name="clerepartition",
            index=models.Index(fields=["axe"], name="analytics_c_axe_id_055a4d_idx"),
        ),
        migrations.AddIndex(
            model_name="clerepartition",
            index=models.Index(
                fields=["date_debut", "date_fin"], name="analytics_c_date_de_789320_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clerepartition",
            unique_together={("societe", "code")},
        ),
        migrations.AddIndex(
            model_name="modeleventilation",
            index=models.Index(
                fields=["compte"], name="analytics_m_compte__0cfc47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modeleventilation",
            index=models.Index(
                fields=["societe", "is_active"], name="analytics_m_societe_09d6e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modeleventilation",
            unique_together={("societe", "code")},
        ),
        migrations.AddIndex(
            model_name="sectionanalytique",
            index=models.Index(
                fields=["axe", "parent"], name="analytics_s_axe_id_203ebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionanalytique",
            index=models.Index(
                fields=["responsable"], name="analytics_s_respons_f0282d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionanalytique",
            index=models.Index(
                fields=["budgetaire"], name="analytics_s_budgeta_53a4d5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sectionanalytique",
            unique_together={("axe", "code")},
        ),
        migrations.AddIndex(
            model_name="repartitionautomatique",
            index=models.Index(
                fields=["compte_source"], name="analytics_r_compte__8efc6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repartitionautomatique",
            index=models.Index(
                fields=["frequence", "is_active"], name="analytics_r_frequen_3c9596_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repartitionautomatique",
            index=models.Index(
                fields=["derniere_execution"], name="analytics_r_dernier_471798_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repartitionautomatique",
            unique_together={("societe", "code")},
        ),
        migrations.AddIndex(
            model_name="lignerepartition",
            index=models.Index(
                fields=["repartition", "ordre"], name="analytics_l_reparti_33076d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lignerepartition",
            index=models.Index(
                fields=["section_destination"], name="analytics_l_section_d160d6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lignerepartition",
            unique_together={("repartition", "section_destination")},
        ),
        migrations.AddIndex(
            model_name="balanceanalytique",
            index=models.Index(
                fields=["societe", "exercice", "periode"],
                name="analytics_b_societe_36da74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="balanceanalytique",
            index=models.Index(
                fields=["section", "periode"], name="analytics_b_section_7e7e2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balanceanalytique",
            index=models.Index(
                fields=["compte", "periode"], name="analytics_b_compte__06fbe7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balanceanalytique",
            unique_together={("section", "compte", "periode")},
        ),
        migrations.AddIndex(
            model_name="tableaubord",
            index=models.Index(
                fields=["societe", "is_active"], name="analytics_t_societe_9586dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tableaubord",
            index=models.Index(fields=["public"], name="analytics_t_public_35e856_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tableaubord",
            unique_together={("societe", "code")},
        ),
        migrations.AddIndex(
            model_name="ventilationanalytique",
            index=models.Index(
                fields=["ligne_ecriture"], name="analytics_v_ligne_e_7bb3a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ventilationanalytique",
            index=models.Index(
                fields=["section"], name="analytics_v_section_aae735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ventilationanalytique",
            index=models.Index(
                fields=["ligne_ecriture", "section"],
                name="analytics_v_ligne_e_0000e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="widgettableaubord",
            index=models.Index(
                fields=["tableau_bord"], name="analytics_w_tableau_0ecd57_idx"
            ),
        ),
    ]
