# Generated by Django 5.2.8 on 2025-11-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0005_alter_mfamethod_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableaubord",
            name="societe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tableaux_bord_analytiques",
                to="core.societe",
            ),
        ),
    ]
