-- ============================================================================
-- Registre des actifs : champs étendus (assurance, garantie, données matérielles,
-- identification, emplacement, acquisition, immobilisation). Rend les onglets du
-- formulaire fonctionnels (saisie + persistance). public.assets ne stockait que
-- le comptable jusqu'ici.
-- (Appliqué en prod le 2026-06-15 ; fichier de parité repo↔prod.)
-- ============================================================================
alter table public.assets
  add column if not exists manufacturer text,
  add column if not exists model text,
  add column if not exists serial_number text,
  add column if not exists barcode text,
  add column if not exists material_data text,
  add column if not exists additional_identifier text,
  add column if not exists weight text,
  add column if not exists dimensions text,
  add column if not exists color text,
  add column if not exists material_type text,
  add column if not exists location text,
  add column if not exists responsible_person text,
  add column if not exists notes text,
  add column if not exists sub_category text,
  add column if not exists warranty_period integer,
  add column if not exists warranty_unit text,
  add column if not exists warranty_terms text,
  add column if not exists warranty_start date,
  add column if not exists warranty_end date,
  add column if not exists warranty_provider text,
  add column if not exists warranty_phone text,
  add column if not exists insurance_provider text,
  add column if not exists insurance_policy_number text,
  add column if not exists insurance_coverage_amount numeric,
  add column if not exists insurance_premium numeric,
  add column if not exists insurance_expiration date,
  add column if not exists policy_type text,
  add column if not exists building_name text,
  add column if not exists floor text,
  add column if not exists room text,
  add column if not exists department text,
  add column if not exists gps_latitude text,
  add column if not exists gps_longitude text,
  add column if not exists location_address text,
  add column if not exists acquisition_type text,
  add column if not exists supplier text,
  add column if not exists invoice_number text,
  add column if not exists invoice_date date,
  add column if not exists purchase_order text,
  add column if not exists delivery_date date,
  add column if not exists commissioning_date date,
  add column if not exists date_mise_en_service date,
  add column if not exists acquisition_currency text,
  add column if not exists transport_cost numeric,
  add column if not exists installation_cost numeric,
  add column if not exists other_costs numeric,
  add column if not exists dotation_account text,
  add column if not exists depreciation_rate numeric,
  add column if not exists depreciation_start_date date,
  add column if not exists revaluation_date date,
  add column if not exists revaluation_amount numeric,
  add column if not exists impairment_amount numeric,
  add column if not exists fiscal_regime text;
