# Generated by Django 5.2.4 on 2025-10-19 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleML",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type_modele",
                    models.CharField(
                        choices=[
                            ("ISOLATION_FOREST", "Isolation Forest"),
                            ("ONE_CLASS_SVM", "One-Class SVM"),
                            ("SVM", "Support Vector Machine"),
                            ("LOF", "Local Outlier Factor"),
                            ("AUTOENCODER", "Autoencoder"),
                            ("KMEANS", "K-Means Clustering"),
                            ("GAUSSIAN_MIXTURE", "Gaussian Mixture Model"),
                            ("DBSCAN", "DBSCAN"),
                            ("LSTM", "LSTM Neural Network"),
                            ("RANDOM_FOREST", "Random Forest"),
                            ("GRADIENT_BOOSTING", "Gradient Boosting"),
                            ("XGBOOST", "XGBoost"),
                            ("PROPHET", "Prophet Time Series"),
                            ("NETWORK_ANALYSIS", "Network Analysis"),
                            ("SYSCOHADA_COMPLIANCE", "SYSCOHADA Compliance"),
                            ("ENSEMBLE", "Ensemble de modèles"),
                            ("CUSTOM", "Modèle personnalisé"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "domaine_application",
                    models.CharField(
                        choices=[
                            ("ECRITURES_COMPTABLES", "Écritures comptables"),
                            ("FLUX_TRESORERIE", "Flux de trésorerie"),
                            ("RATIOS_FINANCIERS", "Ratios financiers"),
                            ("TRANSACTIONS_BANCAIRES", "Transactions bancaires"),
                            ("DECLARATIONS_FISCALES", "Déclarations fiscales"),
                            ("FACTURES_CLIENTS", "Factures clients"),
                            ("FACTURES_FOURNISSEURS", "Factures fournisseurs"),
                            ("PAIE", "Paie et charges sociales"),
                            ("IMMOBILISATIONS", "Immobilisations"),
                            ("STOCKS", "Gestion des stocks"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "parametres_modele",
                    models.JSONField(
                        default=dict, help_text="Paramètres spécifiques au modèle"
                    ),
                ),
                (
                    "features_utilisees",
                    models.JSONField(
                        default=list, help_text="Liste des features/variables utilisées"
                    ),
                ),
                (
                    "preprocessing_config",
                    models.JSONField(
                        default=dict, help_text="Configuration du preprocessing"
                    ),
                ),
                ("date_entrainement", models.DateTimeField(blank=True, null=True)),
                (
                    "donnees_entrainement_periode",
                    models.JSONField(
                        default=dict, help_text="Période des données d'entraînement"
                    ),
                ),
                ("taille_dataset", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "score_performance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Score de performance du modèle (0-1)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "metriques_evaluation",
                    models.JSONField(
                        default=dict, help_text="Métriques d'évaluation détaillées"
                    ),
                ),
                (
                    "seuil_anomalie",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.05"),
                        help_text="Seuil de détection d'anomalie (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "seuil_alerte_critique",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.01"),
                        help_text="Seuil d'alerte critique (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ENTRAINEMENT", "En cours d'entraînement"),
                            ("PRET", "Prêt à utiliser"),
                            ("ERREUR", "Erreur d'entraînement"),
                            ("OBSOLETE", "Obsolète"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ENTRAINEMENT",
                        max_length=20,
                    ),
                ),
                ("derniere_utilisation", models.DateTimeField(blank=True, null=True)),
                ("nombre_predictions", models.PositiveIntegerField(default=0)),
                ("reentrainement_auto", models.BooleanField(default=True)),
                (
                    "frequence_reentrainement",
                    models.PositiveIntegerField(
                        default=30, help_text="Fréquence de réentraînement en jours"
                    ),
                ),
                (
                    "prochaine_reentrainement",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("version_modele", models.CharField(default="1.0", max_length=20)),
                ("hash_modele", models.CharField(blank=True, max_length=64)),
                (
                    "taille_modele_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null pour modèles globaux",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles_ml",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle ML",
                "verbose_name_plural": "Modèles ML",
                "db_table": "apps_ml_detection_modeleml",
                "ordering": ["-date_entrainement"],
            },
        ),
        migrations.CreateModel(
            name="DetectionAnomalie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_anomalie",
                    models.CharField(
                        choices=[
                            ("VALEUR_ABERRANTE", "Valeur aberrante"),
                            ("PATTERN_ANORMAL", "Pattern anormal"),
                            ("SEQUENCE_SUSPECTE", "Séquence suspecte"),
                            ("DEVIATION_TREND", "Déviation de tendance"),
                            ("OUTLIER_CONTEXTUEL", "Outlier contextuel"),
                            ("ANOMALIE_COLLECTIVE", "Anomalie collective"),
                            ("COMPORTEMENT_INHABITUEL", "Comportement inhabituel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "score_anomalie",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Score d'anomalie calculé par le modèle",
                        max_digits=10,
                    ),
                ),
                (
                    "niveau_severite",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYEN", "Moyen"),
                            ("ELEVE", "Élevé"),
                            ("CRITIQUE", "Critique"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "niveau_confiance",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Niveau de confiance du modèle (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "objet_type",
                    models.CharField(help_text="Type d'objet concerné", max_length=100),
                ),
                (
                    "objet_id",
                    models.PositiveIntegerField(help_text="ID de l'objet concerné"),
                ),
                (
                    "donnees_contextuelles",
                    models.JSONField(
                        default=dict, help_text="Données contextuelles de l'anomalie"
                    ),
                ),
                (
                    "features_impactees",
                    models.JSONField(
                        default=list,
                        help_text="Features/variables ayant contribué à la détection",
                    ),
                ),
                (
                    "date_anomalie",
                    models.DateTimeField(help_text="Date/heure de l'anomalie"),
                ),
                (
                    "periode_detection",
                    models.JSONField(
                        default=dict, help_text="Période couverte par la détection"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DETECTEE", "Détectée"),
                            ("EN_COURS_ANALYSE", "En cours d'analyse"),
                            ("VALIDEE", "Validée (vraie anomalie)"),
                            ("FAUX_POSITIF", "Faux positif"),
                            ("RESOLUE", "Résolue"),
                            ("IGNOREE", "Ignorée"),
                        ],
                        default="DETECTEE",
                        max_length=20,
                    ),
                ),
                ("date_analyse", models.DateTimeField(blank=True, null=True)),
                ("commentaire_analyse", models.TextField(blank=True)),
                (
                    "actions_recommandees",
                    models.JSONField(
                        default=list,
                        help_text="Actions recommandées pour traiter l'anomalie",
                    ),
                ),
                (
                    "actions_realisees",
                    models.JSONField(
                        default=list, help_text="Actions réellement effectuées"
                    ),
                ),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                ("impact_estime", models.TextField(blank=True)),
                (
                    "cout_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coût estimé de l'impact",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "analyseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections_anomalies",
                        to="core.societe",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="ml_detection.modeleml",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détection d'Anomalie",
                "verbose_name_plural": "Détections d'Anomalies",
                "db_table": "apps_ml_detection_detectionanomalie",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampagneEntrainement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type_campagne",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Entraînement initial"),
                            ("REENTRAINEMENT", "Réentraînement"),
                            ("MISE_A_JOUR", "Mise à jour"),
                            ("OPTIMISATION", "Optimisation"),
                            ("VALIDATION_CROISEE", "Validation croisée"),
                            ("HYPERPARAMETRES", "Optimisation hyperparamètres"),
                        ],
                        max_length=20,
                    ),
                ),
                ("periode_donnees_debut", models.DateField()),
                ("periode_donnees_fin", models.DateField()),
                (
                    "taille_echantillon",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "strategie_echantillonnage",
                    models.CharField(
                        choices=[
                            ("ALEATOIRE", "Aléatoire"),
                            ("STRATIFIE", "Stratifié"),
                            ("TEMPORAL", "Temporel"),
                            ("COMPLET", "Dataset complet"),
                        ],
                        default="TEMPORAL",
                        max_length=20,
                    ),
                ),
                (
                    "parametres_entrainement",
                    models.JSONField(
                        default=dict,
                        help_text="Paramètres spécifiques à l'entraînement",
                    ),
                ),
                (
                    "validation_split",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.20"),
                        help_text="Proportion des données pour validation (0-1)",
                        max_digits=3,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIEE", "Planifiée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ECHEC", "Échec"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="PLANIFIEE",
                        max_length=15,
                    ),
                ),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("duree_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "score_final",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "metriques_finales",
                    models.JSONField(
                        default=dict, help_text="Métriques finales de performance"
                    ),
                ),
                (
                    "modele_precedent_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Score du modèle précédent pour comparaison",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "amelioration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Amélioration par rapport au modèle précédent",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("log_execution", models.TextField(blank=True)),
                ("erreurs", models.TextField(blank=True)),
                (
                    "ressources_utilisees",
                    models.JSONField(
                        default=dict, help_text="CPU, mémoire, temps, etc."
                    ),
                ),
                ("modele_valide", models.BooleanField(default=False)),
                ("commentaires_validation", models.TextField(blank=True)),
                ("deploye", models.BooleanField(default=False)),
                ("date_deploiement", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes_entrainement",
                        to="core.societe",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes_entrainement",
                        to="ml_detection.modeleml",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne d'Entraînement",
                "verbose_name_plural": "Campagnes d'Entraînement",
                "db_table": "apps_ml_detection_campagneentrainement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegleDetection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type_regle",
                    models.CharField(
                        choices=[
                            ("SEUIL_SIMPLE", "Seuil simple"),
                            ("SEUIL_DOUBLE", "Seuil double (min/max)"),
                            ("VARIATION_RELATIVE", "Variation relative"),
                            ("VARIATION_ABSOLUE", "Variation absolue"),
                            ("PATTERN_TEMPOREL", "Pattern temporel"),
                            ("CORRELATION", "Corrélation"),
                            ("RATIO", "Ratio"),
                            ("SEQUENCE", "Séquence"),
                            ("FREQUENCE", "Fréquence"),
                            ("COMPOSITE", "Règle composite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "champ_cible",
                    models.CharField(
                        help_text="Champ ou métrique à analyser", max_length=100
                    ),
                ),
                (
                    "operateur",
                    models.CharField(
                        choices=[
                            ("GT", "Supérieur à (>)"),
                            ("GTE", "Supérieur ou égal (>=)"),
                            ("LT", "Inférieur à (<)"),
                            ("LTE", "Inférieur ou égal (<=)"),
                            ("EQ", "Égal à (=)"),
                            ("NEQ", "Différent de (!=)"),
                            ("BETWEEN", "Entre deux valeurs"),
                            ("NOT_BETWEEN", "Pas entre deux valeurs"),
                            ("IN", "Dans une liste"),
                            ("NOT_IN", "Pas dans une liste"),
                            ("CONTAINS", "Contient"),
                            ("REGEX", "Expression régulière"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "valeur_seuil",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                (
                    "valeur_seuil_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Pour les seuils doubles",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "conditions_sql",
                    models.TextField(
                        blank=True, help_text="Conditions SQL additionnelles"
                    ),
                ),
                (
                    "parametres_avances",
                    models.JSONField(
                        default=dict,
                        help_text="Paramètres spécifiques au type de règle",
                    ),
                ),
                (
                    "periode_analyse",
                    models.CharField(
                        choices=[
                            ("TEMPS_REEL", "Temps réel"),
                            ("QUOTIDIEN", "Quotidien"),
                            ("HEBDOMADAIRE", "Hebdomadaire"),
                            ("MENSUEL", "Mensuel"),
                            ("PERSONNALISE", "Personnalisé"),
                        ],
                        default="QUOTIDIEN",
                        max_length=20,
                    ),
                ),
                (
                    "fenetre_temporelle",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Taille de la fenêtre temporelle (en unités de période)",
                    ),
                ),
                (
                    "severite_defaut",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYEN", "Moyen"),
                            ("ELEVE", "Élevé"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="MOYEN",
                        max_length=10,
                    ),
                ),
                ("message_alerte", models.CharField(blank=True, max_length=500)),
                (
                    "actions_automatiques",
                    models.JSONField(
                        default=list, help_text="Actions à déclencher automatiquement"
                    ),
                ),
                (
                    "tolerance_faux_positifs",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.05"),
                        help_text="Seuil de tolérance aux faux positifs",
                        max_digits=5,
                    ),
                ),
                (
                    "apprentissage_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Ajustement automatique basé sur les feedbacks",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("derniere_execution", models.DateTimeField(blank=True, null=True)),
                ("prochaine_execution", models.DateTimeField(blank=True, null=True)),
                ("nombre_detections", models.PositiveIntegerField(default=0)),
                (
                    "taux_faux_positifs",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_detection",
                        to="core.societe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de Détection",
                "verbose_name_plural": "Règles de Détection",
                "db_table": "apps_ml_detection_regledetection",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="StatistiqueDetection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("JOUR", "Journalière"),
                            ("SEMAINE", "Hebdomadaire"),
                            ("MOIS", "Mensuelle"),
                            ("TRIMESTRE", "Trimestrielle"),
                            ("ANNEE", "Annuelle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_periode", models.DateField()),
                ("total_detections", models.PositiveIntegerField(default=0)),
                ("detections_critiques", models.PositiveIntegerField(default=0)),
                ("detections_elevees", models.PositiveIntegerField(default=0)),
                ("detections_moyennes", models.PositiveIntegerField(default=0)),
                ("detections_faibles", models.PositiveIntegerField(default=0)),
                ("detections_resolues", models.PositiveIntegerField(default=0)),
                ("faux_positifs", models.PositiveIntegerField(default=0)),
                ("vrais_positifs", models.PositiveIntegerField(default=0)),
                ("en_attente", models.PositiveIntegerField(default=0)),
                (
                    "temps_moyen_resolution_heures",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "temps_max_resolution_heures",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cout_total_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cout_moyen_par_anomalie",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "taux_faux_positifs",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "precision_modele",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "rappel_modele",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiques_detection",
                        to="core.societe",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null pour statistiques globales",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiques",
                        to="ml_detection.modeleml",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique de Détection",
                "verbose_name_plural": "Statistiques de Détection",
                "db_table": "apps_ml_detection_statistiquedetection",
                "ordering": ["-date_periode"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackAnomalie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_feedback",
                    models.CharField(
                        choices=[
                            ("VRAI_POSITIF", "Vrai positif - Anomalie confirmée"),
                            ("FAUX_POSITIF", "Faux positif - Pas d'anomalie"),
                            ("VRAI_NEGATIF", "Vrai négatif - Absence confirmée"),
                            ("FAUX_NEGATIF", "Faux négatif - Anomalie manquée"),
                            ("INCERTAIN", "Incertain - Nécessite investigation"),
                        ],
                        max_length=15,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("cause_identifiee", models.TextField(blank=True)),
                ("solution_appliquee", models.TextField(blank=True)),
                ("prevention_future", models.TextField(blank=True)),
                (
                    "pertinence_detection",
                    models.PositiveSmallIntegerField(
                        help_text="Pertinence de 1 (pas du tout) à 5 (très pertinente)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "utilite_alerte",
                    models.PositiveSmallIntegerField(
                        help_text="Utilité de l'alerte de 1 (inutile) à 5 (très utile)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("suggestions_amelioration", models.TextField(blank=True)),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="ml_detection.detectionanomalie",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Anomalie",
                "verbose_name_plural": "Feedbacks Anomalies",
                "db_table": "apps_ml_detection_feedbackanomalie",
                "ordering": ["-created_at"],
                "unique_together": {("detection", "utilisateur")},
            },
        ),
        migrations.AddIndex(
            model_name="modeleml",
            index=models.Index(
                fields=["company", "domaine_application", "actif"],
                name="apps_ml_det_company_131f50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modeleml",
            index=models.Index(
                fields=["statut", "actif"], name="apps_ml_det_statut_dfeaff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionanomalie",
            index=models.Index(
                fields=["company", "statut", "niveau_severite"],
                name="apps_ml_det_company_3628ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectionanomalie",
            index=models.Index(
                fields=["date_anomalie", "score_anomalie"],
                name="apps_ml_det_date_an_0b608d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectionanomalie",
            index=models.Index(
                fields=["objet_type", "objet_id"], name="apps_ml_det_objet_t_403378_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statistiquedetection",
            unique_together={("company", "modele", "periode", "date_periode")},
        ),
    ]
